### ISSUE TITLE
Leaflet 1.3.0 prevents map plugins from working when detectRetina is true.

### ISSUE THREAD

**Issue by inok6743** [IITC-CE/ingress-intel-total-conversion#106]
Leaflet 1.3.0 has a bug that prevents map plugins from working when ```detectRetina``` is true.
https://github.com/Leaflet/Leaflet/issues/6004#issuecomment-357779141

The bug has been fixed in Leaflet 1.3.1, so I hope that Leaflet used in this project will be updated to 1.3.1 or later.

**Comment by johnd0e** [comment]
This is already fixed by #78, check `test-builds`.

**Comment by inok6743** [comment]
Sorry for overlooking them. Thanks.
