### ISSUE TITLE
layer-count doesn't work after update

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#11]
I suppose it fails after leaflet update: 68cf49f90b75673380167c59b24dd3cfd2aabee3 (though unchecked).

**Comment by modos189** [comment]
I do not quite understand what the problem is :)

**Comment by johnd0e** [comment]
Have you ever use the plugin?
It is intended to measure number of nested fields in arbitrary point of map.

So the steps:
- Activate plugin (click it's icon).
- Chose point at map where we have at least 1-layer field and click there
- See the result near icon

After update I always see "No fields"

**Comment by modos189** [comment]
Interesting. I'll take a look.
