### ISSUE TITLE
is there a date for the next release?

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#112]
We've been waiting a long time, good work 💪

**Comment by johnd0e** [comment]
There is no exact date, but you could track the progress here:
* https://github.com/IITC-CE/ingress-intel-total-conversion/projects/1
* https://github.com/IITC-CE/ingress-intel-total-conversion/milestone/1

And what for do you need next release?
Hint: all new features can be previews in test-builds: https://iitc.modos189.ru/test_builds.html

**Comment by Suburbanno** [comment]
lastest build not loading :(

![screenshot_20190221-100723](https://user-images.githubusercontent.com/13632826/53171245-ee543600-35c0-11e9-9552-3bf0a302fe5c.png)

**Comment by Suburbanno** [comment]
@johnd0e

**Comment by johnd0e** [comment]
Oh, I will check, thanks.

And what about desktop build?

**Comment by Suburbanno** [comment]
I am currently without a desktop to test

**Comment by johnd0e** [comment]
Problem commit was reverted
