### ISSUE TITLE
'About IITC' dialog does not fit screen size

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#113]
Both Mobile and Desktop

**Comment by modos189** [comment]
Why fit screen size on a desktop? Desktop uses windows that are not maximized

**Comment by johnd0e** [comment]
On desktop I see dialog with 'ok' button hidden under bottom edge of the screen

**Comment by johnd0e** [comment]
On mobile we need something like 'fullscreen dialogs'.

We cannot use HTML-only solution, because we need Back button in navigation drawer, which is provided by Java part of our app (see https://github.com/IITC-CE/ingress-intel-total-conversion/commit/b3a42783fad2e42289db9d9a1f6caab9ca1a7230#diff-cb38b2adb39e52661db8963cf7a52d3d).

Current mobile 'panes' are pretty close to what we need. But every pane is listed in left sidemenu, which is not good if we try to use it for plain dialogs.

Thoughts?

**Comment by angel93ayora** [comment]
Any way to redirect the "back" event from java to js?

**Comment by modos189** [comment]
We can pass an event by clicking the Back button, but logic of working with the dialog stack is in the android application, so it is better not to mix them up.

We can add a parameter that disables the creation of an item in left sidemenu. You can open such a dialog box via `android.switchToPane(id);`

**Comment by johnd0e** [comment]
> We can add a parameter that disables the creation of an item in left sidemenu. You can open such a dialog box via `android.switchToPane(id);`

Do you know how to do it?
It's not that simple, as there should be pane with this `id` preregistered with `android.addPane`.

So simplest solution would be this: if there is no pane with specified `id` than open temporary dialog and use `id` as it's title (for actionbar).

BTW, current mobile panes API is far from good at all, and I am thinking about how it could be improved in general (#220).

**Comment by johnd0e** [comment]
It's also should be possible to style jQuery dialog to not exceed width/height.
