### ISSUE TITLE
the colors of the nicks are changing

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#127]
the colors of the names of the players of both factions are being changed, this happens frequently, I have to restart to return to normal, in the latest test build

![screenshot_20190228-104539](https://user-images.githubusercontent.com/13632826/53570967-82d11200-3b46-11e9-844a-4125dcb45fd5.png)
![screenshot_20190228-104510](https://user-images.githubusercontent.com/13632826/53570985-8a90b680-3b46-11e9-8ef7-c9fdd7823f1b.png)

**Comment by johnd0e** [comment]
From your screenshot I see that color of portal itself changes.

And what about stable build? Or 'official' iitc?

**Comment by Suburbanno** [comment]
this build

https://iitc.modos189.ru/build/archive/2019-02-28_13-04/

**Comment by johnd0e** [comment]
I confirm the issue. Now investigating the source.
Thank you for reporting.

**Comment by johnd0e** [comment]
Fixed
