### ISSUE TITLE
Layering issue with plugins

### ISSUE THREAD

**Issue by fortepc** [IITC-CE/ingress-intel-total-conversion#132]
I've got a few plugins from this repo (https://github.com/Wintervorst/iitc/tree/master/plugins) that worked on the iitc.me version, that are now that I've switched to this CE version, not layering properly. I've put an issue on their repo as well as I'm unsure what exactly is at fault.

**Comment by modos189** [comment]
IITC-CE uses the updated Leaflet library, for compatibility with which the authors of third-party plugins need to make some changes.

In this case, changing all `clickable:false` to `interactive:false` solves this problem.

**Comment by fortepc** [comment]
Awesome, thanks for the help.
