### ISSUE TITLE
Sidebar still shows Artifacts while intel no longer has the data

### ISSUE THREAD

**Issue by Tursaanpoika** [IITC-CE/ingress-intel-total-conversion#138]
Plain removal of artifact-related code (lines 2160-2473) breaks IITC, so I commented line 2188 out from my local copy.

**Comment by johnd0e** [comment]
> Plain removal of artifact-related code (lines 2160-2473) breaks IITC, so I commented line 2188 out from my local copy.

Please specify lines in source file [artifact.js](https://github.com/IITC-CE/ingress-intel-total-conversion/blob/master/code/artifact.js).

**Comment by Tursaanpoika** [comment]
oh, basically the whole file (1-311) but commenting out line 30 works.

**Comment by johnd0e** [comment]
> [...] while intel no longer has the data

Well, I agree that artifacts item at toolbox makes not much sense as it always show static text.
But all other code AFAIK is working.

**Comment by Tursaanpoika** [comment]
Yeah, maybe it would be easier to tinker with UI Hide -plugin to add that option too? I'm not too good in this, so I just poke around the compiled code.

**Comment by johnd0e** [comment]
I suppose that we should  just not add artifacts item to toolbox.
So your solution with commenting line 30 is pretty close.

**Comment by johnd0e** [comment]
Ok, I've investigated the issue further, and it seems you misinterpret dialog message.
In fact it means that we has less info about artifacts than before.
But still, if there are some artifacts in view - there should be some info in dialog.

But I agree with you - that message is really confusing, and we shouldn't show it.

And even better: do not show Artifacts link in toolbox until any artifact is really present in view.
