### ISSUE TITLE
IITC Mobile Drawer

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#139]
I know that in the future there will be a redesign, but for the mobile version have you ever thought about a remake in the drawer? Maybe you look more like the traditional drawer, where you have the picture of the account, would it be the photo of the level? where is the name, would be the codename? Where's the "email" would be the AP count and the like ?! What do you think?

I do not have access to the pc to make a draft, sorry.

**Comment by fortepc** [comment]
I do like this a lot!

**Comment by Suburbanno** [comment]
yah, I really hope devs pay special attention to this suggestion.

**Comment by modos189** [comment]
I think this year or next year Niantic will update Intel, so I would not like to cling to the old kind of Intel.
In any case, when the IITC redesign will be considered all proposals.
It would be great to have several designs to choose between the best design.

**Comment by modos189** [comment]
I understand correctly that these suggestions refer to first screenshot from https://github.com/IITC-CE/ingress-intel-total-conversion/issues/18#issuecomment-445544922 ?

**Comment by johnd0e** [comment]
> I understand correctly that these suggestions refer to first screenshot from [#18 (comment)](https://github.com/IITC-CE/ingress-intel-total-conversion/issues/18#issuecomment-445544922) ?

I suppose @Suburbanno wants to move player's info from 'portal info screen' to left drawer.

**Comment by modos189** [comment]
It would be nice

**Comment by Suburbanno** [comment]
https://github.com/IITC-CE/ingress-intel-total-conversion/issues/171
