### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#143]
When we have a lot of features active on map - leaflet performance degrades dramatically.

It's really hard to use map with a lot of portals. And it prevents us to work on #121 (and similar).

It's not clear yet what is the main source of performance lost.
I'm pretty sure that it's not portal markers themselves, as `L.CircleMarker` uses _Canvas_ renderer.

For start, here are some known solutions:
- https://github.com/cyrilcherian/Leaflet-Fullcanvas
- https://github.com/eJuke/Leaflet.Canvas-Markers
- https://github.com/yakitoritabetai/Leaflet.LabelTextCollision

Related issue: #129

**Comment by johnd0e** [comment]
Recently I've seen degraded performance at low zoom levels during Ingress event, when two Europe cities had a lot of portals with ornaments.

**Comment by johnd0e** [comment]
Right now we can observe performance lost over Amsterdam, and it is caused by ornaments. Zooming, panning are extremely slow.
After turning ornaments off performance become normal.

There are now ~1500 ornaments, visualizing by `L.Icon`, and visible even on low zoom levels.

**Comment by modos189** [comment]
Leaflet.Canvas-Markers plugin significantly speeds up work of map with ornaments. But I could not connect it correctly. It seems that there is some conflict over two canvas in page.

**Comment by johnd0e** [comment]
> But I could not connect it correctly.

Have you set up a branch? I would like to look.

**Comment by johnd0e** [comment]
> Related issue: #129

For ornaments we could also try implement some custom 'clustering': detect overlapping markers, and do not draw icons for them.

**Comment by modos189** [comment]
> > But I could not connect it correctly.
> 
> Have you set up a branch? I would like to look.

Yes, here's what I got.

https://github.com/IITC-CE/ingress-intel-total-conversion/commit/1543be0080a22ab58cf52db548df3663b87a1039

**Comment by johnd0e** [comment]
> 1543be0

I see now.
And there are some errors in dev console.
The upstream repo is archived, but can search for fixes in forks: https://github.com/eJuke/Leaflet.Canvas-Markers/network

**Comment by modos189** [comment]
Good news: I took refactored version from https://github.com/Spaction/Leaflet.Canvas-Markers (had to fix a typo, now can't compile) and then there is no conflict between canvas.

Now I need to integrate this with IITC layers

**Comment by johnd0e** [comment]
Great!

> Now I need to integrate this with IITC layers

It is not obvious how to do it best, as we may need to apply canvas markers in other parts of code.
Let discuss it in separate Issue.
