### ISSUE TITLE
[layer-count] Error accessing private property

### ISSUE THREAD

**Issue by Utacka** [IITC-CE/ingress-intel-total-conversion#149]
Not sure where to open the issue, but counting layers plugin is not working properly for me. Either in desktop or mobile iitc. Its not showing anything at all. Works fine with the old(standard) version of iitc available.

**Comment by johnd0e** [comment]
Could you tell exacts versions of IITC-CE, mobile app, and layers-count plugin?
Make sure that you use updated scripts from https://iitc.modos189.ru/

P.S.
For desktop: please note that installing any IITC-CE plugin DOES NOT replace same plugin installed from stock iitc site. So you need to disable/remove old plugins manually.

**Comment by Utacka** [comment]
Everything old is deleted, I installed this fresh. Version 0.29.1 and layers-count 2019-03-15-122355, which I presume is the latest available?:)

**Comment by johnd0e** [comment]
Yes, this is latest, but I am unable to see any problem neither at my desktop nor at mobile:
<details>

![image](https://user-images.githubusercontent.com/1838643/55277381-307f3e80-5308-11e9-9cff-05df9739321f.png)
</details>

Do you see errors in devtools console?
Mobile version also have console (enable in options).

**Comment by Utacka** [comment]
Not really sure how to enable console :p, checked options but i must be blind. Anyway here is a little video on the issue, same issue on desktop.

https://drive.google.com/file/d/124e_0mRp5tabEZAZeNGbUyl__pnS2OuF/view?usp=drivesdk

**Comment by johnd0e** [comment]
> Not really sure how to enable console

Settings/Advanced Settings/Configure IITCm menu: [x] Debug
Then in menu (dots button) you will see Debug checkbox.

But before you continue try clear app data (or uninstall app).
Alternatively: install test-builds apk in parallel.

**Comment by Utacka** [comment]
https://drive.google.com/file/d/1g21DjuSRvy8wDdHB8XjC-WXy7PBp80MY/view?usp=drivesdk

This is without clearing any data, I will try test build a bit later. :)

**Comment by johnd0e** [comment]
> https://drive.google.com/file/d/1g21DjuSRvy8wDdHB8XjC-WXy7PBp80MY/view?usp=drivesdk

There can be more error messages, try to scroll log.

**Comment by Utacka** [comment]
15:46:16.381 ERROR iitcm-console
https://intel.ingress.com/jsc/gen_dashboard_903f20ca9cd00d9a1a46a0db5244b8f6fa9e7757.js:90: Uncaught TypeError: Cannot read property 'style' of null

15:46:16.354 ERROR iitcm-console
https://intel.ingress.com/jsc/gen_dashboard_903f20ca9cd00d9a1a46a0db5244b8f6fa9e7757.js:58: Uncaught TypeError: L is not a constructor

15:46:16.162 WARN iitcm-console
<script/total-conversion-build.user.js>:18132: The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

**Comment by johnd0e** [comment]
Last 3 we may safely ignore.
First 4 are real errors, but in order to identify source I need to see stack, which is easier to do on desktop.
What browser do you use? In Chrome devtools are available on Ctrl-Shift-I.

> I will try test build a bit later. :)

Ok, please do it before we continue

**Comment by Utacka** [comment]
Layer count works fine in test build, it's the only plugin I've enabled.

**Comment by johnd0e** [comment]
Ok. Now try in combination with other plugins. And finally clear data of stable build.

**Comment by Utacka** [comment]
Ive figured out which addon breaks it, the addon is called Enlightened Rocks, which is a private addon from https://enlightened.rocks/ so whenever I sync with that addon, layer count breaks.

**Comment by Utacka** [comment]
Ok, I was wrong. Ive done the same without enl rocks plugin, i manually just pasted drawn items in drawtools options and layer counts break. There seems to be some kind of connection with draw tools and then layer count breaking.

**Comment by johnd0e** [comment]
Confirmed, any draw is enough.

I believe that you are able to reproduce the issue with stock IITC too if you enable **canvas** renderer.
