### ISSUE TITLE
Числа с плавающей точностью делают ссылки на порталы битыми

### ISSUE THREAD

**Issue by ReinRaus** [IITC-CE/ingress-intel-total-conversion#152]
Воспроизведение:

Открыть IITC-CE
Нажать на любой портал
Открыть панель INFO портала
Нажать PERMALINK

Результат:

https://intel.ingress.com/intel?ll=68.90692013938536,33.1039309501648&z=16

Точность позиционирования портала до долей миллиметра.

**Comment by ReinRaus** [comment]
https://intel.ingress.com/intel?ll=68.906194,33.103192&z=16 

Такая ссылка должна быть на самом деле.

**Comment by johnd0e** [comment]
**Permalink** is position of map itself.
You need **Portal link**.

**Comment by ReinRaus** [comment]
Sorry
