### ISSUE TITLE
Samsung Dex Mode

### ISSUE THREAD

**Issue by Whomiga** [IITC-CE/ingress-intel-total-conversion#156]
Is it possible to add the capability to open in Desktop mode by default when in Samsung Dex Mode, or even have a Setting for "Open in Desktop when in Samsung Dex Mode"?

Having the setting would allow for normal Smartphone mode (not desktop) and Samsung Dex mode (desktop) without having to flip the current setting when changing environments.

**Comment by johnd0e** [comment]
I suppose it's possible:
https://program.developer.samsung.com/2017/07/27/samsung-dex-how-to-detect-the-samsung-dex-mode/

**Comment by Whomiga** [comment]
I finally managed to get a copy to compile and run, I'm going to take a look at this capability myself.

**Comment by Whomiga** [comment]
I have a test version that works, but I need to test it a bit, of course and determine if it is the best way to do it,
Appears to work quite well, how do I go about contributing the changes?

**Comment by johnd0e** [comment]
Implemented by #161
