### ISSUE TITLE
Curiosities / general questions about the IITC and its use.

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#159]
- How does the IITC really work?
- How many requests does it make?
- Is detectable by niantic? 
- Does the IITC flood the server in any way?
- is it safer to use IITC without plugins or with?
I have several curiosities about IITC, I am an old user and would like to understand the whole process ...

**Comment by johnd0e** [comment]
> How does the IITC really work?
> How many requests does it make?

It works pretty much like stock intel.

> Is detectable by niantic?

Well, they could if they care.
Although iitc tries to mimic stock intel behavior, there are some minor differences anyway.

> Does the IITC flood the server in any way?
> is it safer to use IITC without plugins or with?

Of course IITC and all official plugins do not flood the server.
But it's possible to write plugin which do.
