### ISSUE TITLE
IITCm signin layout

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#160]
After recent intel update there is new button which does not fit well:
<details>

![IITC screenshot-1288478869](https://user-images.githubusercontent.com/1838643/55887450-343b7c80-5bb6-11e9-94ed-4ffcba2a4b5f.png)

</details>

**Comment by modos189** [comment]
Well, actually, it's a Niantic problem, not an IITC

**Comment by johnd0e** [comment]
@modos189 
I'm not sure: in browser all is ok.

**Comment by modos189** [comment]
Niantic has completed maintenance on the Intel Map and now the buttons look better.

<details>
<summary>Details</summary>

![изображение](https://user-images.githubusercontent.com/1785196/55982596-ea2fc500-5ca1-11e9-90e8-7f23063b8602.png)

</details>

**Comment by johnd0e** [comment]
Your font looks different.
Unfortunately mine stays the same..

**Comment by johnd0e** [comment]
The easiest way to fix it - change style, something like this: 
```
.button { white-space: nowrap; margin: 6px }
```

But I still suppose that there can be more proper way.

**Comment by modos189** [comment]
If we make changes to the form of authorization, I suggest to make it more convenient for the touch screen. Placed the buttons in the column and now they are entirely clickable, not just a link inside the buttons.

<details>
<summary>Details</summary>

![photo_2019-04-13_21-27-13](https://user-images.githubusercontent.com/1785196/56083845-f39c6700-5e32-11e9-808a-978e0ba36dff.jpg)

</details>

```
#dashboard_container {
    display: flex;
    flex-direction: column;
}

.button {
    margin: 5px 10px;
    padding: 0;
}

#dashboard_container a {
    display: block;
    padding: 10px 15px;
}
