### ISSUE TITLE
Bookmarks reorder error (& fix)

### ISSUE THREAD

**Issue by angel93ayora** [IITC-CE/ingress-intel-total-conversion#166]
**Versions:**
bookmarks: 0.2.12.20190315.122355
iitc-ce: 0.29.1.20190315.122355

**Enabled plugins:**
iitc-ce, bookmarks

**Problem:**
reordering portals is failing
reordering folders is failing
moving portals between folders is failing

**How to reproduce:**
create some bookmarks and/or folders to test the reordering, collapse the bookmarks box and re-open it

**How to fix:**
(lines 626 and 639 of downloaded bookmarks plugin from iitc.modos189.ru)
in function: `window.plugin.bookmarks.jquerySortableScript`
  in both `update` handlers
    change `+ui.item.context.id` per `+ui.item[0].id`

(!) This should be caused due to jquery updates, search for item.context on the entire codebase is suggested.

**Comment by johnd0e** [comment]
@angel93ayora 
Thank you for reporting!

Please check if latest of test-builds is working properly now.
