### ISSUE TITLE
Permanent signature for debug build

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#17]
_Originally posted by @modos189 in https://github.com/IITC-CE/ingress-intel-total-conversion/issues/12#issuecomment-444803540_

Please make some signature in order to let each new debug build to be installed over previous one.

**Comment by modos189** [comment]
done

https://github.com/IITC-CE/ingress-intel-total-conversion/commit/444650e6cf8b8b09ebea0cc540e3702666edaa89
https://github.com/IITC-CE/ingress-intel-total-conversion/commit/3ca24dfd220203607e24daf22d6b1fc610d97e5e
https://github.com/IITC-CE/ingress-intel-total-conversion/commit/fc1092e8e493fa025590d000a36a1a539be65009
