### ISSUE TITLE
IITCm menu: direct link to Plugins settings

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#18]
I need access Plugins settings a lot more than any other setting item.
It would be convenient to have direct link to it in menu.
It may be optional (`Advanced Settings` / `Configure IITCm menu`).

**Comment by modos189** [comment]
I generally want to update the design. The local community has already made preparations.
I also want to rework the menu for plugins.

![photo_2018-12-09_17-55-54](https://user-images.githubusercontent.com/1785196/49698999-a9814b80-fbdc-11e8-8ab7-b1a7c73d0302.jpg)
<img width="1592" alt="desktop" src="https://user-images.githubusercontent.com/1785196/49699001-a9814b80-fbdc-11e8-8902-a6231c85b12f.png">


It is important, of course, not to lose the IITC functions.

**Comment by johnd0e** [comment]
> I generally want to update the design. 

Good to know! I like the pictures.
Official iitc design extremely needs improvements.

I also have some ideas (not visual but rather functional), but I think that better discuss them in separate issues.

> I also want to rework the menu for plugins.

Do you mean https://github.com/iitc-project/ingress-intel-total-conversion/pull/1232, or something else?

**Comment by modos189** [comment]
> https://github.com/iitc-project/ingress-intel-total-conversion/pull/1232
no, that's different. I would like to have a search for plugins, but there is a bad implementation, and I do not know java to do it myself.

I mean, when you install a lot of plugins, the toolbar gets very clogged. We need to figure something out.

Probably, McBen has begun [work in this direction](https://github.com/McBen/ingress-intel-total-conversion/commit/c1ad34eec8f7a9c2520cc7cd91773dd85979b993), has not yet looked

**Comment by johnd0e** [comment]
> Probably, McBen has begun work in this direction, has not yet looked

Right.
And we even not have to implement it in core, e.g. see `Free Sidebar` plugin: http://www.giacintogarcea.com/ingress/items/

But this plugin is not perfect solution.
In my opinion we should logically separate all controls into 3 groups:
1. info and actions on selected portal
2. other actions
3. options

Only 1st have to be tied to portal info, other better to be movable.

**Comment by johnd0e** [comment]
P.S.
I am no sure that it's directly related, but here I saw something related to controls grouping: https://github.com/hayeswise/ingress-intel-total-conversion/blob/master/plugins/wise-helper-toolbox-control-section.js

(can be seen in couple of plugins https://github.com/hayeswise/)

**Comment by johnd0e** [comment]
And trying to return to subject of this issue:

> I also want to rework the menu for plugins.

In this issue I mean only this menu:
![image](https://user-images.githubusercontent.com/1838643/49732130-3fbd7c00-fc86-11e8-978c-8f319a69b256.png)

And here I would like to add 1 item: Plugins, which lead directly to corresponding section of Settings.
