### ISSUE TITLE
Toasty beacon not showing

### ISSUE THREAD

**Issue by carlobolla** [IITC-CE/ingress-intel-total-conversion#187]
![immagine](https://user-images.githubusercontent.com/14152206/57174741-a1ec6880-6e43-11e9-9c76-27a3c3d40bd4.png)

Toasty beacon is showing this error on the Intel Map

"ornaments": [
    "peTOASTY"
  ],

**Comment by carlobolla** [comment]
I think i should mention: version is 0.29.1.20190315.122355

**Comment by johnd0e** [comment]
Could you provide Intel map url where we can see this beacon?

**Comment by johnd0e** [comment]
![peTOASTY.png](https://commondatastorage.googleapis.com/ingress.com/img/map_icons/marker_images/peTOASTY.png)

It's not on ingress server storage, so I doubt that even stock Intel is able to show it correctly.

**Comment by carlobolla** [comment]
https://intel.ingress.com/intel?ll=22.614785,120.306668&z=17&pll=22.614785,120.306668

Thank you for clarification! I guess we'll have to wait for it then

**Comment by johnd0e** [comment]
May be you should report it to Niantic, as stock intel has the same issue.

![image](https://user-images.githubusercontent.com/1838643/57177999-e3e0d300-6e72-11e9-9f7f-e88805e079f8.png)

![image](https://user-images.githubusercontent.com/1838643/57178033-6bc6dd00-6e73-11e9-9681-541bd24bab93.png)

**Comment by appastair** [comment]
https://gist.github.com/appastair/9042b1b80f2dab3f97db20774c00809c
