### ISSUE TITLE
removeLayerGroup throws "Layer was not found" for valid layers

### ISSUE THREAD

**Issue by McBen** [IITC-CE/ingress-intel-total-conversion#190]
it's a bug in the old iitc code. Never arises because the "_leaflet_id" was equal to the entry in the layerchooser.
This is no longer the case in leaflet 1+

Bug Fix:
```
diff --git a/code/utils_misc.js b/code/utils_misc.js
index 39865ce3..7d5fbdb1 100644
--- a/code/utils_misc.js
+++ b/code/utils_misc.js
@@ -409,9 +409,11 @@ window.addLayerGroup = function(name, layerGroup, defaultDisplay) {
 }
 
 window.removeLayerGroup = function(layerGroup) {
-  if(!layerChooser._layers[layerGroup._leaflet_id]) throw('Layer was not found');
+  const layerEntry = layerChooser._layers.find( entry => entry.layer === layerGroup);
+  if(!layerEntry) throw('Layer was not found');
+
   // removing the layer will set it's default visibility to false (store if layer gets added again)
-  var name = layerChooser._layers[layerGroup._leaflet_id].name;
+  var name = layerEntry.name;
   var enabled = isLayerGroupDisplayed(name);
   map.removeLayer(layerGroup);
   layerChooser.removeLayer(layerGroup);

```

**Comment by johnd0e** [comment]
Do you know any real plugin using this function?

P.S.
The issue is known https://github.com/IITC-CE/ingress-intel-total-conversion/issues/163#issuecomment-482785398, but I am going to refactor the whole `layerChooser`, in order to get rid of all these supplementary functions (still keeping stubs for compatibility).

**Comment by McBen** [comment]
> Do you know any real plugin using this function?

My private build. I already replaced that code for myself but maybe other authors will face the same problem.

Function is working in iitc but broken in iitc-ce. (even when the bug already exists in the old code)

> The issue is known #163 (comment)

Good to hear you'll refactor that part too. Maybe you should change the label of the issue to be more informative.

**Comment by modos189** [comment]
Thanks for fix. I think we can accept it until johnd0e rewrites layerChooser.

**Comment by johnd0e** [comment]
@modos189
Please note that we avoid ES6 in our code.
This function is unused, I suppose we don't have heavy need to fix it separately.

**Comment by modos189** [comment]
Not used by us, but if used by private plugins, we can fix it.
But, of course, we need to remake, don't use ES6.
Anyway, it's not hard

**Comment by johnd0e** [comment]
Well, I am almost sure that nobody uses it, even in private plugins)
But I may be wrong, need to check McBen's Layers control.

**Comment by McBen** [comment]
> Well, I am almost sure that nobody uses it, even in private plugins)

atleast me was using it and got reports of user that my plugin won't work with iitc-ce
if noone (else) uses it: remove it instead of leave unfunctional code inside.

> But I may be wrong, need to check McBen's Layers control.

Thats a complete other topic. I did my layer-control long time ago and if I remember right it's a complete replacement (with still bugs inside)

**Comment by johnd0e** [comment]
> atleast me was using it and got reports of user that my plugin won't work with iitc-ce

That is another matter.
What exactly plugin do you mean?

**Comment by McBen** [comment]
> 
> 
> > atleast me was using it and got reports of user that my plugin won't work with iitc-ce
> 
> That is another matter.
> What exactly plugin do you mean?

none you know

**Comment by McBen** [comment]
anyway...you want it, you got it 
heres a amazing plugins which doesnt work -> https://github.com/McBen/johnd0eExample

works in every iitc version. except iitc-ce

**Comment by johnd0e** [comment]
@McBen
#108: IITC 'api' is very extensive, as every minor internal function is (potentially) available to plugins. But in fact there is relatively small subset of functions that are (really) used by plugins.
In process of refactoring IITC internals inevitable changes, and I do not see any sense to keep every old function interface 'just in case'.

But real plugins using it - another matter, as we trying to maintain compatibility. 
I have downloaded a lot of plugins for exact this purpose: check real API usage.
So my question was about real plugins, not hypothetical ones.
 
~~BTW, your sample plugin has error in function usage, and unable to work in your own fork.
(And if your have layer instance then you do not need IITC API to remove it, just use leaflet's `removeLayer`)~~

**Comment by McBen** [comment]
sad to here...so I've to keep writing iitc-ce workaround to keep my users happy.
'cause iitc-ce will increase incompabilty with old iitc code.

you don't even mind how many code is out there you will never see. Bad for us all some of these aren't maintained anymore.

**Comment by johnd0e** [comment]
I'd be happy to fix any reported incompatibility.

**Comment by McBen** [comment]
I did here

**Comment by McBen** [comment]
> BTW, your sample plugin has error in function usage, and unable to work in your own fork.
> (And if your have layer instance then you do not need IITC API to remove it, just use leaflet's `removeLayer`)

as said -5min code- quickly checked. should work (if initialized in correct order)
`removeLayer `and `removelayergroup `are doing different things

**Comment by modos189** [comment]
I found use of `removelayergroup()` function in this secret resistance plugin
reswue.user.js

**Comment by McBen** [comment]
could you please add s.t.r.i.k.e code too

**Comment by McBen** [comment]
and maybe drunkenfrog or riot or what ever none plublic code you know

**Comment by modos189** [comment]
I have no idea what you're talking about)

**Comment by McBen** [comment]
yeah..me too..seems totally wired to request fixing a function which is totally bugged in iitc-ce

**Comment by modos189** [comment]
What? I don't see reason not to fix
