### ISSUE TITLE
Inconsistent errors throwing

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#191]
1. `throw 'string'`
2. `throw new Error 'string'`
3. `throw {error: 'string'}`

Mostly 1st used.
2nd is better, but mobile debug console is able to handle plain strings only.

I suppose we should fix console.

**Comment by johnd0e** [comment]
> I suppose we should fix console.

It's here: https://github.com/IITC-CE/ingress-intel-total-conversion/blob/master/mobile/app/src/main/java/org/exarhteam/iitc_mobile/Log.java

@modos189 
Could you look it?

**Comment by HubertZhang** [comment]
A backup for discussion in telegram

Currently Android's WebView could only pass string message to host application. And these message are actually generated use Object.toString(). Thus `throw new CustomError("message")` would just give the host application `[object Object]`.

If we want to fetch more information in host application, we have to format that message before throw or just implement the `toString()` method
