### ISSUE TITLE
pogo-s2 plugin isn't working with IITC-Button on Chrome

### ISSUE THREAD

**Issue by fortepc** [IITC-CE/ingress-intel-total-conversion#192]
This plugin works just fine with IITC-CE inside of tampermonkey, but doesn't appear to even try to load when it's inside of IITC-Button. 

The plugin is here: https://gitlab.com/AlfonsoML/pogo-s2

The plugin has a few Pokemon Go centric features, such as flagging a portal as a Gym or Pokestop, being able to overlay S2 cells of adjustable sizes, and highlight S2 Cells that are full and cannot accept any new submissions.

Reporting issue on both repos because I'm not sure where the issue actually is. 
Issue on their repo: https://gitlab.com/AlfonsoML/pogo-s2/issues/40

**Comment by johnd0e** [comment]
> Reporting issue on both repos because I'm not sure where the issue actually is.

Actually you should report it here: https://github.com/IITC-CE/IITC-Button/issues

(I suspect that IITC-Button does not provide `unsafeWindow` to scripts.)

**Comment by fortepc** [comment]
ah! yes that's a good point. I'll go do that. I hadn't realized at the time of writing that it had it's own repo. 
https://github.com/IITC-CE/IITC-Button/issues/5
