### ISSUE TITLE
link-show-direction: issues with canvas rendering

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#20]
This is not new issue, but previously it was not important, because canvas mode was experimental and optional.

So, plugin has 5 different modes, and only 2/5 are usable now:
- Static
- Animate full link

Honestly, I do not think that all 5 are worthful (for me, the only useful mode was `Static near origin`).
May be we need to think about some different way of visualization.

**Comment by modos189** [comment]
I use `Animate near origin`. I think we should keep all 5 options, someone they can be comfortable
