### ISSUE TITLE
Bookmarks plugin stopped working

### ISSUE THREAD

**Issue by mxxcon** [IITC-CE/ingress-intel-total-conversion#208]
Running latest stable version of Chrome
IITC-CE Version: 0.26.0.20181031.195523 [iitc-test]
All other plugins are also up to date.
When I click on the `*` in portal details window the portal doesn't get added to the bookmarks and instead of I see the following error in the console log:

![image](https://user-images.githubusercontent.com/847140/58980044-77bcfc00-879d-11e9-894c-2dbe3704d6db.png)

**Comment by modos189** [comment]
0.26? But that's old version. Last release is 0.29.1 version https://iitc.modos189.ru/download_desktop.html

However, an error was found when sorting bookmarks, but it is already fixed in the test build https://github.com/IITC-CE/ingress-intel-total-conversion/issues/166

**Comment by mxxcon** [comment]
You are right. Brain fart on my end. Invalid issue. Sorry to bother you.
