### ISSUE TITLE
Plugin read/update issues

### ISSUE THREAD

**Issue by angel93ayora** [IITC-CE/ingress-intel-total-conversion#210]
I've enconteured two problems:

1. Read issue. When in-script key-value headers are separated with tabs (instead of spaces) the app will crash and will not be able to start properly until the plugin is deleted or tabs are replaced with spaces.
This happened to me when i've updated a plugin with tabs and encountered that iitcm was crashing :/

2. Update issue. When `plugin-name.meta.js` file exists and is readable, and a request to `plugin-name.user.js` returns almost anything the file placed on `plugins` folder will be replaced with that response. That response could be a 404 html, or something.
Possible solutions:
-- Check content-type http header
-- Check for in-script version / id headers

**Comment by johnd0e** [comment]
1. Perhaps it is function of this code: https://github.com/IITC-CE/ingress-intel-total-conversion/blob/256f9c53a866a254b40e40b1f766e58b4d2a89f4/mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_FileManager.java#L107-L120

**Comment by johnd0e** [comment]
2. It's here: https://github.com/IITC-CE/ingress-intel-total-conversion/blob/256f9c53a866a254b40e40b1f766e58b4d2a89f4/mobile/app/src/main/java/org/exarhteam/iitc_mobile/async/UpdateScript.java#L66-L76

**Comment by johnd0e** [comment]
@angel93ayora 
Please check test build

**Comment by johnd0e** [comment]
>  -- Check for in-script version / id headers

Most proper way:
- make sure that script has the same `namespace` and `name` (perhaps for meta.js this should to be done too)
- `version` value is same as specified in meta.js
