### ISSUE TITLE
Loading details...

### ISSUE THREAD

**Issue by 54D** [IITC-CE/ingress-intel-total-conversion#211]
IITC is unable to display any portal information, even after map loading is "done".
 [![Screenshot from Gyazo](https://gyazo.com/4ed31c1f921518c277370972dde0ae0c/raw)](https://gyazo.com/4ed31c1f921518c277370972dde0ae0c)

This seems to be an issue with IITC as I am able to view resonator, mod info and more when IITC is not enabled.

**Comment by johnd0e** [comment]
Could you provide exact steps to reproduce this issue (incl. map permalink)?
What do you see in dev console (F12)?
What if you disable plugins?
Does it happen with old stock IITC too?
And please attach here 'About IITC' screenshot.

**Comment by 54D** [comment]
### Could you provide exact steps to reproduce this issue (incl. map permalink)?
This issue happens to all portals. 
The portal above is this link: https://intel.ingress.com/intel?pll=22.287346,114.161344
 1. Open intel.ingress.com. (ingress.com/intel also works.)
 2. Zoom in to anywhere, and left click on any portal.
 3. Wait for a few minutes.
### What do you see in dev console (F12)?
2 errors thrown when I left click any portal:
```
gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:76 Uncaught TypeError: Cannot read property 'children' of null
    at Rg (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:76)
    at vo (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:283)
    at HTMLDocument.uo (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:276)
    at sc (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:22)
    at HTMLDocument.nc (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:24)
    at HTMLDocument.b (gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:20)
Rg @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:76
vo @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:283
uo @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:276
sc @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:22
nc @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:24
b @ gen_dashboard_a4178e36700aafb4da150e9777b70c465583f82e.js:20
```
```
VM200:1 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at HTMLDocument.document.createElement (<anonymous>:1:4065)
    at window.escapeHtmlSpecialChars (<anonymous>:24237:22)
    at <anonymous>:24260:40
    at Function.map (<anonymous>:16687:3367)
    at window.genFourColumnTable (<anonymous>:24258:13)
    at window.getPortalMiscDetails (<anonymous>:20999:48)
    at window.renderPortalDetails (<anonymous>:20827:31)
    at handleResponse (<anonymous>:20735:7)
    at <anonymous>:20755:39
    at Object.onSuccess (<anonymous>:23323:7)
```
### What if you disable plugins?
Same results no matter what plugins are enabled / disabled.
### Does it happen with old stock IITC too?
If you're referring to the old IITC, yes.
### And please attach here 'About IITC' screenshot.
Certainly.
[![Screenshot from Gyazo](https://gyazo.com/6775002286865b41aada4f6505a588d0/raw)](https://gyazo.com/6775002286865b41aada4f6505a588d0)

**Comment by johnd0e** [comment]
From your About info I can't figure out what version is.
Please update to [stable](https://iitc.modos189.ru/download_desktop.html) or [test-builds](https://iitc.modos189.ru/test_builds.html).

And I am still unable to reproduce the issue.
What browser do you use? And what userscript manager?

You may try to reboot, or use another browser.

**Comment by modos189** [comment]
This is last test build, but I unable to reproduce too.
Besides, 54D use IITC Button because specific gen_dashboard message.

**Comment by johnd0e** [comment]
> This is last test build

Yes, the timestamps exactly match. But where is main version component?

**Comment by johnd0e** [comment]
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/256f9c53a866a254b40e40b1f766e58b4d2a89f4/code/utils_misc.js#L303-L309
Perhaps there should be `  var div = document.createElement('div');` instead.

@54D 
Could you confirm if that this change solves the issue?

**Comment by 54D** [comment]
### Please update to stable or test-builds.
Indeed I'm using IITC Button installed from the [Chrome Web Store](https://chrome.google.com/webstore/detail/iitc-button/febaefghpimpenpigafpolgljcfkeakn).

### What browser do you use? And what userscript manager?
Currently using Google Chrome, 64-bit, version 75.0.3770.100 official build.
Before I switched to IITC Button, I was using Tampermonkey 4.8.41.

### You may try to reboot, or use another browser.
Rebooting my computer this morning (approx. 3 hours ago) surprisingly fixed the issue. I have been experiencing this on two of my other computers for the past month. 

### Perhaps there should be var div = document.createElement('div'); instead.
Should I still implement this change if my has been fixed? The same error from gen_dashboard is still being thrown.

**Comment by johnd0e** [comment]
> Rebooting my computer this morning (approx. 3 hours ago) surprisingly fixed the issue.

I've already updated IITC test-builds, that's why it got fixed.

No, you do not implement anything.

gen_dashboard is exception from stock intel. It's more cosmetic issue, just ignore it.
