### ISSUE TITLE
UI color

### ISSUE THREAD

**Issue by Suburbanno** [IITC-CE/ingress-intel-total-conversion#22]
is there the ability to change the UI theme according to the faction? and who knows a redesign? ta well outdated, btw good work on reliving this beautiful project!!

![iitcui](https://user-images.githubusercontent.com/13632826/49774922-868a9080-fcdd-11e8-8b1d-805e82a00399.PNG)

![itcuidark](https://user-images.githubusercontent.com/13632826/49775167-627b7f00-fcde-11e8-86a0-caf8283f657f.PNG)

**Comment by modos189** [comment]
Now this is not possible, but if someone makes a plugin, it would be good.

Anyway, the design will be upgraded in the future https://github.com/IITC-CE/ingress-intel-total-conversion/issues/18#issuecomment-445544922

**Comment by johnd0e** [comment]
>  but if someone makes a plugin, it would be good.

I think it shouldn't be hard.

BTW, I see there are several unrelated styles for every UI element.
It would be nice to reorginize css to make slyles inherited (#90).

> Anyway, the design will be upgraded in the future

I suppose this also can be done via plugin.

**Comment by johnd0e** [comment]
@Suburbanno

> is there the ability to change the UI theme according to the faction?

I can make a plugin for this if you provide desirable colors values (for both factions).

**Comment by Suburbanno** [comment]
#2ecc80 ENL
#2571ea RES

**Comment by johnd0e** [comment]
Are these `color` or `background-color`?
I see that background is transparent on your screens, so we need some opacity value.
And active chat tab has own value.

**Comment by Suburbanno** [comment]
related: https://github.com/IITC-CE/ingress-intel-total-conversion/issues/90 https://github.com/IITC-CE/ingress-intel-total-conversion/issues/185
