### ISSUE TITLE
Sync not syncing

### ISSUE THREAD

**Issue by joselsegura** [IITC-CE/ingress-intel-total-conversion#222]
Hi!

I moved a few days ago from IITC to IITC-CE. I was using Sync plugin with a lot of problems When testing if sync works with this plugin, I saw that a IITC-SYNC-DATA-V3 directory was created on my GDrive, but no files are stored at all.

I have a lot of info stored at my computer local installation (uniques) that I don't want to lose. Losing keys or bookmarks is not a problem since I was not using them a lot... but I want to preserve my uniques.

Do you know some workflow that allow me to "upload" my uniques info to the sync folder and get them into my IITC-CE mobile client?

P.S. I tried with the test-build branch version, but apparently I have the same behavior

**Comment by modos189** [comment]
Can you show a screenshot of Sync window?

**Comment by joselsegura** [comment]
Sync on PC: https://drive.google.com/file/d/1E_PAzr9YSzwMFvt9HiMxT5Ka833CQMYK/view?usp=sharing
Sync on Mobile: https://drive.google.com/file/d/1_q5TgGzf0G0n4mjcpfRs2f5LpaVsr1P0/view?usp=sharing

Not so much info in that screenshots... Right now I'm running the 0.3.1.20190315.122355 version in both sides

**Comment by johnd0e** [comment]
> right now I'm running the 0.3.1.20190315.122355

It is outdated. Please make screenshots of 0.4

**Comment by modos189** [comment]
@johnd0e I'm seeing error in test build. You did nothing with Events?

![изображение](https://user-images.githubusercontent.com/1785196/61056019-57ffa000-a3fb-11e9-9a9d-9f64420f7f66.png)

**Comment by johnd0e** [comment]
> You did nothing with Events?

Sure I did: #205.
And your IITC seems not latest, as there is no such check anymore: https://github.com/IITC-CE/ingress-intel-total-conversion/pull/205/commits/fd2ac7c79c662797d7a791c9e40687c1d31a258a#diff-cb52e6e0624ee384d4fc5f9d675b30a3L101

**Comment by joselsegura** [comment]
I installed Sync (and only Sync) from test_build branch and now there is no "Sync" link to open the sync window...
Do I need to update the rest of the plugins? Is there any quick way to do that?

**Comment by johnd0e** [comment]
> Do I need to update the rest of the plugins?

Update main script: https://iitc.modos189.ru/build/test/total-conversion-build.user.js

**Comment by modos189** [comment]
I get it, only changes are saved

**Comment by joselsegura** [comment]
https://drive.google.com/file/d/1mWHQSk-butjruQDdciv7DEpaONriGdPn/view?usp=sharing

**Comment by vidarak** [comment]
> Do you know some workflow that allow me to "upload" my uniques info to the sync folder and get them into my IITC-CE mobile client?
> 
https://github.com/c-schmitz/iitc-unique-export/raw/master/IngressUniqueExporter.user.js

**Comment by MysticJay** [comment]
We have been testing the updated uniques (PR#378). This included test with SYNC as well.
All data seemed to be handled as expected.
Even with the mobile versions not currently supporting the new fields in the UI the data still gets handled correct.
But having a backup from the exporter is always a good idea.

The next version of uniques will integrate the exporter (thanks @c-schmitz).

**Comment by MysticJay** [comment]
There is no evidence of a problem with SYNC, nor any other related reports.

The proposed workaround solves the issue of migrating UNIQUES form IITC.me to IITC-CE
> https://github.com/c-schmitz/iitc-unique-export/raw/master/IngressUniqueExporter.user.js

Closing case
