### ISSUE TITLE
Draw2 

### ISSUE THREAD

**Issue by MysticJay** [IITC-CE/ingress-intel-total-conversion#223]
1) create an alternative to draw-tools ("Draw2-beta") that will allow to switch, while it would not break the pending PRs.
2) enable Draw2 for MPE (to allow showing the functionality)
3) review draw-related PRs and create a list of ideas from them
4) decide and merge
_Originally posted by @MysticJay in https://github.com/IITC-CE/ingress-intel-total-conversion/issues/219#issuecomment-510525301_

**Comment by johnd0e** [comment]
Draw2 meant to be draw-tools + integrated mpe/draw-plus?
Or something else?

**Comment by MysticJay** [comment]
right in the end it shall replace the old draw

**Comment by johnd0e** [comment]
> 2\. enable Draw2 for MPE (to allow showing the functionality)

What does it mean?

**Comment by MysticJay** [comment]
From Zaso's Drawtools plus:

- [x] Merge draws
- [x] Empty Draw Fields
- [x] Export, Export w. empty Polygons, Export to stock Intel

**Comment by johnd0e** [comment]
It would be great if we refactored that numerous menu tools into more tidy subset + options.
- Export
  - [ ] Stock
- Import
  - [ ] Merge
- Type
  - [ ] File
  - [ ] String

As for 'empty polygons', I suppose it can be separate action for current draw (without need to be exported)

P.S.
It is just common idea, interface may be different.

Currently I do not like that
- "Copy Drawn Items" looks similar to "Export Drawn Items"
- "Paste Drawn Items" looks similar to "Import Drawn Items"

More: https://t.me/iitc_group/744, https://t.me/iitc_group/800

**Comment by johnd0e** [comment]
I've just realized that Draw Plus on desktop lacks *file* functionality.
And on mobile it lacks other part of functionality (export to intel).

It should be fixed.
