### ISSUE TITLE
Sync Error by accessing the RegisteredMap

### ISSUE THREAD

**Issue by Haspelknecht** [IITC-CE/ingress-intel-total-conversion#227]
I have some trobules with the sync/unique mechanism.
The version on sync: 0.4.0.20190708.161546.

I get on my console :
VM2549:118 Uncaught TypeError: Cannot set property 'de20a3c65ec6475bb475554a766857d4.16' of null
    at String.<anonymous> (<anonymous>:118:24)
    at Function.each (<anonymous>:16693:2777)
    at window.plugin.sync.RegisteredMap.updateMap (<anonymous>:115:7)
    at Function.window.plugin.sync.updateMap (<anonymous>:55:17)
    at <anonymous>:295:15

In the end the "map[]" field is not set in the function window.plugin.sync.RegisteredMap.prototype.updateMap

**Comment by MysticJay** [comment]
@Haspelknecht
Which Versions of SYNC and UNIQUES are you using?
did you try, using the new prerelease versions?

**Comment by MysticJay** [comment]
IMHO something has tampered with the data, but the only modules we can see, that act on `uniques` are
SYNC and UNIQUES:

![grafik](https://user-images.githubusercontent.com/25123137/92590044-d1af4a00-f29b-11ea-8c1e-62ee331b8218.png)

The `map[]` (see error msg) is only a pointer to the original data-object `uniques`.
At no point in the code any element gets deleted from `uniques`.
(even if all action checkmarks are removed they only get set to "false").

I looked into this and can not find a point, how the function window.plugin.sync.updateMap can be called with a GUID that is no longer part of the data object `uniques`.

We can add an additional check to avoid the alert, but that would not resolve the cause.
Fact is it should not be able to happen at all, but as it does, it is better to trigger an error.

**Comment by MysticJay** [comment]
Can be closed. Problem was related to Beta-Build of uniques.
