### ISSUE TITLE
Store previous developer builds for easy testing

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#24]
It would be convenient in order to search exact build where some regression occurred.
But we need to mark apk somehow, may be by appending sha-hash to it's name.

**Comment by johnd0e** [comment]
> https://github.com/IITC-CE/ingress-intel-total-conversion/commit/0db821dcd246886a1f16b8fbda8bfc5527f0505e

So are they already available to download?

**Comment by modos189** [comment]
Not yet

**Comment by modos189** [comment]
Now available to download
https://iitc.modos189.ru/test_builds.html

**Comment by johnd0e** [comment]
Great, thank you!

BTW, I have an issue with website: it's content does not get updated.
Workaround: clear cache or press Ctrl-F5.

I am not sure but may be there is some problem in web server setup?

**Comment by modos189** [comment]
I have disabled caching for html documents. This should fix the problem.

**Comment by johnd0e** [comment]
Thanks!
