### ISSUE TITLE
[Layer Count] - Error and doesn't work on Firefox 68.0.2 on Linux

### ISSUE THREAD

**Issue by Athanasius** [IITC-CE/ingress-intel-total-conversion#247]
// @version        0.1.0.20190315.122355
// @description    [release-2019-03-15-122355] Allow users to count nested fields
// @updateURL      https://iitc.modos189.ru/build/release/plugins/layer-count.meta.js
// @downloadURL    https://iitc.modos189.ru/build/release/plugins/layer-count.user.js
// @namespace      https://github.com/IITC-CE/ingress-intel-total-conversion

Nothing appears to happen when pressing the Layer Count icon/button.  Firefox Console shows:

TypeError: el is undefined line 25310 > scriptElement:3724:6
    removeClass https://intel.ingress.com/ line 25310 > scriptElement:3724
    onBtnClick https://intel.ingress.com/ line 235 > scriptElement:44
    eachLayer https://intel.ingress.com/ line 25310 > scriptElement:8260
    onBtnClick https://intel.ingress.com/ line 235 > scriptElement:39

Which doesn't match up with anything in Issue #149

**Comment by Athanasius** [comment]
And yes, I'll sort out nuking all data and trying latest test build....

**Comment by johnd0e** [comment]
@Athanasius https://iitc.modos189.ru/test_builds.html

**Comment by Athanasius** [comment]
Yup, this works on the test build.  I've not been keeping track, do you have a release cadence/plan ?
