### ISSUE TITLE
Remove broken stuff

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#25]
- [ ] https://github.com/iitc-project/ingress-intel-total-conversion/issues/1297
- [ ] https://github.com/iitc-project/ingress-intel-total-conversion/issues/1296
- [ ] https://github.com/iitc-project/ingress-intel-total-conversion/issues/1295
- [x] [fixed] https://github.com/iitc-project/ingress-intel-total-conversion/issues/1271

**Comment by johnd0e** [comment]
@modos189 
So what do you think? Should we attach this to milestone:"IITC-CE v0.29"?

**Comment by modos189** [comment]
Yes, it's not much work.

**Comment by johnd0e** [comment]
* `basemap-opencyclemap.user.js`
  See https://github.com/IITC-CE/ingress-intel-total-conversion/issues/2#issuecomment-460566051
* fix-googlemap-china-offset: unfunctional now, will be replaced (#68)
* portal-highlighter-debug: unfunctional
