### ISSUE TITLE
FlyLinks some modify

### ISSUE THREAD

**Issue by durck** [IITC-CE/ingress-intel-total-conversion#258]
I slightly modified the plugin. In toolbox, added a button that moves to the draw tools links from flyLinks

**Comment by durck** [comment]
It is interesting for your?

**Comment by johnd0e** [comment]
Hard to say from that brief description.
Could you show some code, or screenshots?

**Comment by durck** [comment]
1. Enable flyLinks
![Enable plugin](https://user-images.githubusercontent.com/31553806/65335019-4b05e680-dbcc-11e9-890a-67ba58eb15b5.png)

2. When we set view where we want work with plugin push button "Drow FlyLinks"
![InkedPush Button](https://user-images.githubusercontent.com/31553806/65335294-d7180e00-dbcc-11e9-8793-147996dd81f3.jpg)

3. We can disable plugin. We have:
![dt](https://user-images.githubusercontent.com/31553806/65335379-00389e80-dbcd-11e9-8789-fe4334bec355.png)

**Comment by durck** [comment]
[fly-links.user.zip](https://github.com/IITC-CE/ingress-intel-total-conversion/files/3636432/fly-links.user.zip)

**Comment by durck** [comment]
is it interesting or no?

**Comment by johnd0e** [comment]
@durck Sure it is.
Similar features were requested long time ago.

**Comment by durck** [comment]
you are will add this feature in the plugin? or i can to do it?

**Comment by johnd0e** [comment]
@durck I have not tried your implementation yet. So I do not know if we can add it 'as is'.

You could submit a PR. It'd be useful for further discussion.
