### ISSUE TITLE
Debug output: make conditional

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#26]
iitc writes a lot of debug info to console log, but it's not useful for general use, and only adds 'noice' to log.
It would be more useful if such thing were wrapped in something like this:

```
function window.debug.log (info) {
  if (window.debug.ENABLE_LOG) {
    console.log (info)
  }
}
```
Condition could be more complex:

```
function window.debug.log (level,info) {
  if (debug.ENABLE_LOG.ALL or debug.ENABLE_LOG[level]) {
    console.log (info)
  }
}
```

In order to control the condition ENABLE_LOG we could use additional plugin.

**Comment by johnd0e** [comment]
May be we should use some library.

- https://github.com/jonnyreeves/js-logger
- https://github.com/download/ulog
   Seems good:
   > It has AWESOME debug features. Just set `DEBUG=module1,module2` and these modules will start logging debug info
  - https://github.com/Download/ulogv2
  - https://github.com/download/anylogger#readme
- https://github.com/visionmedia/debug#readme
- https://github.com/pimterry/loglevel
- ~~https://github.com/gajus/roarr~~ 
- http://log4javascript.org/
- https://github.com/loggin-js/loggin-js
- custom: https://t.me/iitc_group/724,
https://t.me/iitc_group/1221

**Comment by angel93ayora** [comment]
What would be the requirements of a logger?

filter by levels?
filter by tags?

i think that exporting the log stack to a string could be useful to present a user the logs without opening the dev tools, could be useful for mobile devices. Showing it at the hidden debug tab at comm or from the about IITC for example.

**Comment by johnd0e** [comment]
See comment in upper post. May be similar functionality in other form.

**Comment by johnd0e** [comment]
> could be useful for mobile devices.

IITCm has own console.

**Comment by angel93ayora** [comment]
>> could be useful for mobile devices.

> IITCm has own console.

yes, also desktop has, for less experienced users could be simplier
that is only an idea, totally optional

**Comment by johnd0e** [comment]
@angel93ayora Well, may be. We could add 'share log' link to 'about iitc' dialog.

**Comment by johnd0e** [comment]
Another feature that I would like to have: optional popup notifications about errors.

Most of time we use iitc with closed console window, so we need to be notified about errors somehow.

It may be simple notification, or even pop-out console replacement.

**Comment by angel93ayora** [comment]
i think that feature is not present on any of the libraries you said

**Comment by angel93ayora** [comment]
my logger supports modules while storing all messages on the same stack, you can filter by module and level/minLevel and the filtered result can be printed through console or retrieved as a string

also not depending on a external library would give us the chance to insert desired features, like the one you said

**Comment by johnd0e** [comment]
`log4javascript` has some similar.
And I can list more (like `erudaconsole`).

Actually I do not expect that out-of-the-box, but want our logger to have some relevant extension-points.

E.g. `ulog` has 'formatters' feature, which possibly can be hooked for our purposes. Haven't tried thought.

**Comment by johnd0e** [comment]
@angel93ayora Yeah, I will try to setup both.

I do not mind against custom logger, but as every new custom code - it needs debugging itself. There may be some unexpected caveats, etc.
