### ISSUE TITLE
Can't use facebook login to intel with IITC-CE on android

### ISSUE THREAD

**Issue by SoundGuy** [IITC-CE/ingress-intel-total-conversion#263]
When app starts, i try to log in to intel map using facebook it opens up the separate browser app and tries to log in there instead of opening a browser window within the up to login like it does when trying to log in with google
then it stays there and the login screen remains the same inside iitc-ce

my google account isn't available anymore so i need to use the facebook login, which i do on ingress but i can't do it on IITC

**Comment by modos189** [comment]
@SoundGuy Thanks for your report. Fixed in https://github.com/IITC-CE/ingress-intel-total-conversion/issues/164

Please use test build https://iitc.modos189.ru/test_builds.html

**Comment by SoundGuy** [comment]
Ha! it works. thanks
