### ISSUE TITLE
About IITC is broken on platform not using GM api

### ISSUE THREAD

**Issue by HubertZhang** [IITC-CE/ingress-intel-total-conversion#269]
When `GM_info` is empty, `script_info` will have no `script` property and About IITC dialog won't show up

**Comment by johnd0e** [comment]
@HubertZhang So fill GM_info

**Comment by johnd0e** [comment]
@HubertZhang 
Could you specify what exact part of code causes that error?

This?
```js
  var iitcVersion = iitc.script.version + ' [' + iitc.buildName + ']';
```

**Comment by HubertZhang** [comment]
`iitc = script_info`
and in https://github.com/IITC-CE/ingress-intel-total-conversion/blob/5456b0c9a23641caa13be3d40a1222d0f30134bb/main.js#L11
`script_info = plugin_info `

and `plugin_info` is initialized by https://github.com/IITC-CE/ingress-intel-total-conversion/blob/5456b0c9a23641caa13be3d40a1222d0f30134bb/pluginwrapper.py#L37

So if `GM_info` not exist, `iitc.script` is `undefined`, access `iitc.script.version` will throw exception

Also `iitc.buildName` is not set and will become `undefined` in About IITC dialog
