### ISSUE TITLE
Not all portals loading since last week

### ISSUE THREAD

**Issue by asdfjkll2** [IITC-CE/ingress-intel-total-conversion#280]
Since last week multiple people I know have been having problems where not every single portal loads on the map at times, it seems very odd that as much as half the portals in the area fail to load and they have not been removed (they are still in-game). All layers are turned on, so its not that. See attached pictures.
![missing portals 1](https://user-images.githubusercontent.com/18220769/70164381-ae110080-1686-11ea-903c-559e5b4f9d82.PNG)
![missing portals 2](https://user-images.githubusercontent.com/18220769/70164382-aea99700-1686-11ea-802a-af8bfca501a5.PNG)
![missing portals 3](https://user-images.githubusercontent.com/18220769/70164383-aea99700-1686-11ea-8cce-fdae04905a57.PNG)

**Comment by johnd0e** [comment]
@asdfjkll2 Do you observe same issue with  stock intel?

**Comment by asdfjkll2** [comment]
No I do not, in the third picture is the same area on stock intel, which loads just fine.

**Comment by johnd0e** [comment]
@asdfjkll2 Please show screens of About IITC and debug console.

**Comment by asdfjkll2** [comment]
![iitc latest](https://user-images.githubusercontent.com/18220769/70165275-3ba12000-1688-11ea-88e6-aeb7fa30efb0.PNG)
![dev console](https://user-images.githubusercontent.com/18220769/70165295-465bb500-1688-11ea-8a59-686f6684494b.PNG)
Chrome Dev console
It happened again in another area, i circled a couple areas where portals failed to load

**Comment by johnd0e** [comment]
@asdfjkll2 Scroll (or filter) console to make sure that there are no errors.
And try latest test build.

Could you specify map permalink where we could observe the issue?

**Comment by asdfjkll2** [comment]
I scrolled up and down the console and saw no errors. Permalinks to where I observed the issue are at https://intel.ingress.com/intel?ll=30.393341,-86.435578&z=15 , https://intel.ingress.com/intel?ll=33.190682,-87.480928&z=15 , https://intel.ingress.com/intel?ll=30.522589,-86.473207&z=15, or basically in random area anywhere.

**Comment by johnd0e** [comment]
@asdfjkll2 I am still failing to reproduce

**Comment by modos189** [comment]
@asdfjkll2 Does the problem repeat after the page reloads?
Indeed, now there are problems with caching in Intel, both in IITC and Intel. I found several cases where portals were not displayed in Intel, but when opening this address in IITC-there were displayed.

**Comment by elkuku** [comment]
this seems do happen these days in stock intel so - NIA bug :|

**Comment by KenAlin** [comment]
Hi,
I have the same problem. Sometimes, randoms portals are missing, but reappear after a few minutes.

But I believe this is a problem from Niantic servers. Here is a quick network comparison between two IITC tabs : one where a specific portal is missing, the other where the same portal is not missing on the map. Zoom level and coordinates are exactly the same.

![image](https://user-images.githubusercontent.com/12164749/70393026-26105b00-19e6-11ea-83d2-1f922444a990.png)

As you can see, getEntities requests are the same, but responses are different. In the first case, the portal in not in json response. In the second case, the portal is present.

=> Not an IITC problem.

**Comment by perringaiden** [comment]
This is a known issue with the Intel cache right now.  Refresh a few times and it'll show up on both IITC and Intel.

**Comment by Timo-V** [comment]
Nothing is loading anymore for me now. Everything fails.
