### ISSUE TITLE
IITC-Mobile: versionCode will be wrong for shallow clones

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#284]
Currently [`versionCode`](https://developer.android.com/guide/topics/manifest/manifest-element#vcode) value is generated by this command:
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/f3f5ebd79112d56ad8b370fe08c800a1b1b5592a/mobile/app/build.gradle#L6

In case of our repo clone is shallow - we get wrong number.

Perhaps we should make sure here that repo is not shallow, may be put `git fetch --unshallow` to `build.gradle`.
(But there is pitfall: https://stackoverflow.com/questions/28001878/git-fetch-unshallow-gives-fatal-unshallow-on-a-complete-repository-does-n#35124035)

**Comment by modos189** [comment]
fixed in https://github.com/IITC-CE/ingress-intel-total-conversion/pull/305
