### ISSUE TITLE
draw-tools touch issues in 0.30.1

### ISSUE THREAD

**Issue by WadeNZL** [IITC-CE/ingress-intel-total-conversion#315]
Creating links and fields on Android is no longer 1 touch. 
Example. I have to drag finger on screen to bring up cursor and 2nd press on screen to create a valid choice. Too make valid Points for App to acknowledge selection.
Best way could describe it. Sorry

**Comment by johnd0e** [comment]
What is your iitc version?
Did it worked in proper way before? In what version?
Tell us about your device: is it phone or tablet? What android version does it have?
Also:  try to update system WebView from Google Play.

**Comment by johnd0e** [comment]
I confirm the issue.
Workaround: Advanced settings / Fake UserAgent.

**Comment by johnd0e** [comment]
Please check test build:
https://iitc.modos189.ru/build/test/IITC_Mobile-test.apk
https://iitc.modos189.ru/build/test/plugins/draw-tools.user.js
