### ISSUE TITLE
Add Uniques visited/captured to Portal CSV Exporter

### ISSUE THREAD

**Issue by D64134n0** [IITC-CE/ingress-intel-total-conversion#321]
Please add Uniques visited/captured to Portal CSV Exporter

**Comment by johnd0e** [comment]
What is 'portal csv exporter' and why should we care about it?

**Comment by D64134n0** [comment]
Ooops, I'm sorry. My mistake.

Regarding to what is "Portal CSV exporter" it is a very useful plugin for iitc that can be found here http://github.com/Zetaphor/IITC-Ingress-Portal-CSV-Export

And regarding to why should you care, you shouldn't.  I posted the request in the wrong project and I'm closing it now.

Again, sorry for the inconvenience.
