### ISSUE TITLE
style: sidebar and sidebartoggle do not have the same Z-index

### ISSUE THREAD

**Issue by le-jeu** [IITC-CE/ingress-intel-total-conversion#363]
When using a screen small enough (half a screen for instance), the `sidebartoggle` is above the chat while the sidebar content is below the chat.

Using Firefox 77:
![image](https://user-images.githubusercontent.com/64744459/84569149-9aa4c780-ad84-11ea-8b72-537b9edb4b8b.png)

I suggest to use the same z-index for `#sidebar`, `#sidebartoggle` and `#scrollwrapper` to 3001 (chat using 3000 as z-index).

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/85ce020bfc32b00be005e65736f637607a14b2c4/core/style.css#L59-L100

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/85ce020bfc32b00be005e65736f637607a14b2c4/core/code/boot.js#L419-L426

**Comment by modos189** [comment]
Let's set z-index: 2999 for `#sidebartoggle`. Then this button will be below `#chat`, but above `#scrollwrapper`

**Comment by johnd0e** [comment]
If someone is still interested in these fixes - please put them into PR.

@le-jeu @modos189
