### ISSUE TITLE
Using draw-tools on Android app is hard 

### ISSUE THREAD

**Issue by clavelm** [IITC-CE/ingress-intel-total-conversion#368]
I'm using iitc-ce 0.30.1 on Android 10 LineageOS 17.1.
When drawing a polyline or a polygon from draw-tools, it's very hard to click on portals to start, add a point, or click on the last point to finish the draw.
I need to click and again and again, but not too fast or else it's zooming. I still don't know why sometimes it's working but most of the time not.
Last polyline, I had to finish the line near the last portal, then edit to move the point on the portal (or use snap to portal).
Draw-tools on iitc.me don't have the same problem.
I'm using another plugin with no relation to draw-tools to draw fields, and selecting a portal is working as intended, so it's draw-tools on iitc-ce the problem.

**Comment by johnd0e** [comment]
Please show your About IITC screen with all plugins listed.

**Comment by clavelm** [comment]
![_20200627_130320](https://user-images.githubusercontent.com/717388/85920753-af9a5400-b876-11ea-8f66-3d38be5b913a.JPG)
I don't know how to display all the plugins versions on the iitc-ce Android app.

**Comment by johnd0e** [comment]
Not this. Open it from toolbox

**Comment by clavelm** [comment]
![IMG_20200627_131005](https://user-images.githubusercontent.com/717388/85920847-934ae700-b877-11ea-9329-3acdaffab30e.jpg)

**Comment by johnd0e** [comment]
Ok, now try more recent https://iitc.app/build/test/IITC_Mobile-test.apk

**Comment by clavelm** [comment]
It's working good. The only problem is when trying to close a polyline on a portal that already has a point. It's not registering it.

**Comment by johnd0e** [comment]
@clavelm Right.
Workaround: place last point somewhere near portal, and then use edit tool.
Or better use polygon for closed shapes

**Comment by clavelm** [comment]
Yes its working with polygons.
So this issue can be closed I think.
