### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by suread** [IITC-CE/ingress-intel-total-conversion#373]
IITC v 0.30.1 on Vivaldi 3.1 /Chrome 83 on Windows 10

Load intel.ingress.com with development console open, IITC only active Tampermonkey script.

Expected: intel loads without exception thrown.
Actual: Exception is thrown as map is loaded.

Exception is thrown by ark.js - but since it only happens when IITC is active, it looks like an IITC issue.

**Comment by johnd0e** [comment]
`ark.js` is some 'leftover' of stock intel code.
IITC code does not use any stock code directly, but for technical reason it requires stock for bootstrap.
After that IITC completely rewrites the whole webpage, and it's no surprise that stock intel is unable to finish some actions.

It seems that `ark.js` is some recent addition to stock intel, but we observed similar effects earlier, e.g. see https://github.com/iitc-project/ingress-intel-total-conversion/issues/964.

It is not the bug, it's rather minor cosmetic issue. But feel free to open PR if you find some way to prevent the exception.

**Comment by suread** [comment]
Yes, I realise ark.js is Niantic's, not IITC - but since the exception only happens when IITC is running I am looking at IITC as the cause. (Just as I look at my own plugin if IITC only throws an exception if my plugin is active)
Cosmetic? For most people yes, but it is definitely disconcerting when trying to work on plugins and you have an extra error to figure out.

**Comment by johnd0e** [comment]
> I am looking at IITC as the cause

Sure it is.
