### ISSUE TITLE
Draw Tools Options / color selector

### ISSUE THREAD

**Issue by MysticJay** [IITC-CE/ingress-intel-total-conversion#381]
What is causing this broken style for the palette?
![grafik](https://user-images.githubusercontent.com/25123137/88486457-e5b61b00-cf7d-11ea-882a-89a8c93915aa.png)

0,30.1 (release) with DT 0.7.1 does not show this.
0.30.1 (release) with DT 0.8.0 does not show this
0.30.1.20200720.132610 [test] with DT 0.8.0 shows problem

**Comment by McBen** [comment]
tracked it down to:
0c90913bb863597c4b4f66ff37c0fe182120a493 - external: update jQuery to 3.5.1 

PR: https://github.com/IITC-CE/ingress-intel-total-conversion/pull/369

**Comment by McBen** [comment]
But the full truth is:
It's a bug in spectrum: https://github.com/bgrins/spectrum/issues/563

a missing `</span>` in plugins/external/spectrum.js#143
should be:
`html.push('<span title="' + formattedString + '" data-color="' + tiny.toRgbString() + '" class="' + c + '"><span class="sp-thumb-inner" style="' + swatchStyle + ';" /></span></span>');`

**Comment by johnd0e** [comment]
[Quickfix](https://jquery.com/upgrade-guide/3.5/#a-workaround):
```js
var rxhtmlTag = /<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi;
jQuery.htmlPrefilter = function( html ) {
    return html.replace( rxhtmlTag, "<$1></$2>" );
};
```

**Comment by johnd0e** [comment]
> a missing `</span>` in plugins/external/spectrum.js#143

True. And [that](https://github.com/bgrins/spectrum/blob/master/spectrum.js#L143) is [already fixed](https://github.com/bgrins/spectrum/pull/556) in upstream, so we need just upgrade spectrum to latest.

**Comment by MysticJay** [comment]
Confirming issue solved. still this is a workaround and night need to be reverted.
![grafik](https://user-images.githubusercontent.com/25123137/89107736-51dbc780-d433-11ea-9dee-9a67591bbd2b.png)

**Comment by MysticJay** [comment]
Solution accepted.
upgrade provided with PR#382
