### ISSUE TITLE
IITC not supported?

### ISSUE THREAD

**Issue by Whomiga** [IITC-CE/ingress-intel-total-conversion#384]
Appears that Google will not let IITC sign in at  all
![20200809_110902](https://user-images.githubusercontent.com/39813882/89736697-de3c4a80-da30-11ea-94ac-49261b3f7d03.jpg)

**Comment by johnd0e** [comment]
@Whomiga Show your About IITC Mobile screen.

**Comment by Whomiga** [comment]
![Screenshot_20200809-112324_IITC Mobile](https://user-images.githubusercontent.com/39813882/89736934-d7163c00-da32-11ea-9552-578c4994b858.jpg)

**Comment by Whomiga** [comment]
I'll force an update and recheck it, stand by...

**Comment by Whomiga** [comment]
Looks like my old version suddenly failed, appears to be no issue with the latest release at present
Sorry for the inconvenence, closing the issue.
