### ISSUE TITLE
eval() blocked by Firefox

### ISSUE THREAD

**Issue by MysticJay** [IITC-CE/ingress-intel-total-conversion#386]
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/3f4867a4a4ab5dd86d093fcaa9829f3267f70e9b/core/code/chat.js#L777

Firefox blocks execution of eval(). the result is an Error in the console.

`Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). Source: (function(a,B,u,V){let n,m,b,w,H,y,S,G,ea,t,fa,L,ka;const d={};let e={safeWindow:d,safeDocument:{},eval,Context:{D:V},exec_fn:function(a,b,e){n(new d.Function(a),b,e)},exec_csp:function(a,b,d){const c=`__u__${19831206*e.Context.M_r()+1}`;e.Message.send("csp",{id:c,src:a});e.exec_script(c,b,d)},exec_script:function(b,d,e){const c=a[b];delete a[b];n(c,d,e)}};const I=(b,d)=>{a.console.error(`Tampermonkey sandbox preparation ${d?"("+`

**Comment by McBen** [comment]
can't confirm.  
And would be really bad for any webpack-development code.

How do you run the "debug" chat tab on firefox?   I'm not even sure if this code is used on mobile.

**Comment by McBen** [comment]
![grafik](https://user-images.githubusercontent.com/29117/90959477-afe05580-e49b-11ea-80a6-cadee2d5a88d.png)
faked a debug tab

**Comment by McBen** [comment]
I believe this error message is sync-plugin / google api related.

**Comment by MysticJay** [comment]
Wasn't the line with the eval introduced for ulog?
I was also wondering how it got executed, but it ws the only one found in the code.

Google API is a good guess, at it causes more messages, that maybe can be avoided by not loading that from the web.

**Comment by johnd0e** [comment]
> Wasn't the line with the eval introduced for ulog?

I has nothing with ulog.
And I even have no idea how to enable that 'debug' tab.
It is sort of legacy code and we have no plans to support it anyway.
