### ISSUE TITLE
Uniform code style

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#39]
In current code base we can see now a variety of different styles.
It would be great to bring everything to some common code style.

So let's discuss here:

1. Elements of iitc-code uniform style 

2. Tools to implement style checking, and ways to include them in our CI-chain.

**Comment by johnd0e** [comment]
So if we prefer to keep existing style's elements then we should use [eslint](https://eslint.org).
Otherwise, we could use some 'opinionated' formatter, like [prettier](https://prettier.io) or [StandardJS](https://standardjs.com/).

**Comment by modos189** [comment]
Project code style is specified in
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/master/HACKING.md#code-style

But eslint only reports discrepancy to code style? I think utility itself should format code to our style

**Comment by johnd0e** [comment]
> Project code style is specified in
> https://github.com/IITC-CE/ingress-intel-total-conversion/blob/master/HACKING.md#code-style

Great. I will make `.eslintrc` with that rules.

> But eslint only reports discrepancy to code style?

There is `--fix` option.
But not all issues could be resolves automatically.

>  I think utility itself should format code to our style

`prettier` is even more automatic, but it's rules are predefined, so we can use it only if we agree with the whole style.

P.S.
Anyway, we need to merge all old PR's before any global changes.

**Comment by johnd0e** [comment]
BTW, found inconsistency in the document.
Here is a rule:
> * there should be a space after `if`, `for`, etc. E.g. `if (true) { doStuff(); } else { dontDoStuff(); }`

But see at example two lines upper:
> * opening brace on the same line: `if(blub) {`

**Comment by johnd0e** [comment]
And perhaps we need to add some other rules to the list.
E.g. https://eslint.org/docs/rules/semi

**Comment by johnd0e** [comment]
Here is the same specification with eslint rules' references added (`.eslintrc` will follow).
Perhaps we should add some more rules, so consider it's still a draft.

Code Style
----------

Please follow the these guidelines. Some are just preference, others are good practice.
- IITC sources currently meet [ES 5.1][ES5] standard
- [eqeqeq]: use identity operators: `===` and `!==`. [Why do I want this?](http://stackoverflow.com/a/359509/1684530)
- jQuery is your friend
- [indent] using two spaces
- enforce [semi]colon
- _'one true [brace-style]'_:
  - opening brace on the same line: `if (blub) {`
  - else clauses: `} else if (blub) {` or `} else {`
- [keyword-spacing]: there should be a space after `if`, `for`, etc.
   E.g. `if (true) { doStuff(); } else { dontDoStuff(); }`
- [spaced-comment]: `// this is a comment`
- [quotes]: Use single-quotes for JavaScript and double-quotes for HTML content. Example: `$('body').append('<div id="soup">Soup!</div>');`.
- there is no length limit on lines, but try to keep them short where suitable
- [no-trailing-spaces]: ensure you remove *all* trailing whitespace before submitting your patch. If you editor doesn’t detect those for you, try `grep -nE "[[:space:]]+$" «filename»`

[indent]: https://eslint.org/docs/2.0.0/rules/indent
[quotes]: https://eslint.org/docs/2.0.0/rules/quotes
[semi]: https://eslint.org/docs/2.0.0/rules/semi
[brace-style]: https://eslint.org/docs/2.0.0/rules/brace-style
[keyword-spacing]: https://eslint.org/docs/2.0.0/rules/keyword-spacing
[no-trailing-spaces]: https://eslint.org/docs/2.0.0/rules/no-trailing-spaces
[spaced-comment]: https://eslint.org/docs/2.0.0/rules/spaced-comment
[eqeqeq]: https://eslint.org/docs/2.0.0/rules/eqeqeq
[ES5]: https://www.ecma-international.org/ecma-262/5.1/
