### ISSUE TITLE
IITCm Android, octant direction not shown unless fully deployed

### ISSUE THREAD

**Issue by sthen** [IITC-CE/ingress-intel-total-conversion#392]
The octant direction is shown on the portal info page for a fully deployed portal, but not if resonators are missing

**Comment by McBen** [comment]
this data is not available.

see:
 // note: as of 2014-05-23 update,

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/3f4867a4a4ab5dd86d093fcaa9829f3267f70e9b/core/code/portal_detail_display_tools.js#L139
