### ISSUE TITLE
Google Authorization doesn't work on Safari on iOS 13.2

### ISSUE THREAD

**Issue by crystalwizard** [IITC-CE/ingress-intel-total-conversion#396]
Google Error 403: disallowed_useragent when trying to authenticate with iitc-ce build 30.1  The workaround
![photo5156657849089239145](https://user-images.githubusercontent.com/17938346/94465644-129ccf00-0175-11eb-89d3-63d212c254ba.jpg)
![photo5156657849089239149](https://user-images.githubusercontent.com/17938346/94465646-13356580-0175-11eb-946f-15e743f3501d.jpg)
![photo5156657849089239150](https://user-images.githubusercontent.com/17938346/94465648-13356580-0175-11eb-94ad-f45665c1338e.jpg)

 is: Settings -> Set Custom useragent for webviews.

**Comment by johnd0e** [comment]
Wrong repo.
Go to https://github.com/HubertZhang/IITC-Mobile
