### ISSUE TITLE
Time Since Last Activity Can Be Negative

### ISSUE THREAD

**Issue by jbreazeale** [IITC-CE/ingress-intel-total-conversion#398]
![Screenshot 2020-10-09 131834](https://user-images.githubusercontent.com/2078057/95618045-0694f500-0a32-11eb-9360-197bd9ac803d.png)
The attached screen shot is from today, October 9, 2020 over Farmington, MN.  See the -1 minute since the last activity.

**Comment by MysticJay** [comment]
@jbreazeale system time not in sync with intel

**Comment by jbreazeale** [comment]
I checked the system time with an app that is based upon the atomic clock.  The system time is very close to the atomic clock time.  How about just show a zero instead of a negative one?

**Comment by MysticJay** [comment]
@jbreazeale check the comm for a diff in times
