### ISSUE TITLE
Can't login using Google with IITCm Test: Error 403 disallowed_useragent

### ISSUE THREAD

**Issue by Athanasius** [IITC-CE/ingress-intel-total-conversion#402]
Google objects to the user agent.

Android 10 on Google Pixel 2 XL, 5 July 2020 update. Firefox as default browser.

![Screenshot_20200730-091028.png](https://user-images.githubusercontent.com/118007/88898482-b2f17880-d244-11ea-9886-2448b0851949.png)

**Comment by modos189** [comment]
In this situation can also help install/update [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview)

**Comment by johnd0e** [comment]
@Athanasius 
Have you tried @modos189 suggestion?

**Comment by Athanasius** [comment]
I think I ignored that at the time because I was using an official Pixel 2 XL ROM which of course has, and keeps updated, WebView.

My comment above had solved it for me and then I didn't have any issue again.
