### ISSUE TITLE
Draw Tools can't draw a line on iOS14.

### ISSUE THREAD

**Issue by ishiis** [IITC-CE/ingress-intel-total-conversion#405]
DrawTools cannot draw lines, shape, circle and marker.

DrawTools button is displayed, but DrawTools cannot be drawn line when clicking this button.

I'm using the latest version of IITC on iOS14.

**Comment by johnd0e** [comment]
Please make sure that you are using latest test version (release version is outdated).

**Comment by johnd0e** [comment]
I assume the issue is resolved. Feel free to reopen.
