### ISSUE TITLE
Volatile Scout Controller Portals break IITC-CE

### ISSUE THREAD

**Issue by MaxEtMoritz** [IITC-CE/ingress-intel-total-conversion#410]
Volatile Scout Controller Portals have just gone live. Now IITC fails to load the Portal data.
the Error is
```Uncaught TypeError: this._container is undefined```
it happens at a method called _checkDisplay() that my browser shows me exactly [here](https://github.com/IITC-CE/ingress-intel-total-conversion/blob/803f3f77d90d9982f7e53d6a9e687083842ee73d/core/external/leaflet.canvas-markers.js#L116). That's an older version of the file as i see now, but this may not be the only problem with the new changes made by Niantic...

More Info on what this is can be found e.g. on the Community Forum:
https://community.ingress.com/en/discussion/12903/volatile-scout-controller-portals

**Comment by MysticJay** [comment]
@MaxEtMoritz Issue aleady resolved in test-builds.
fix is in PR#360

**Comment by MaxEtMoritz** [comment]
sorry, found that out now, too 🤦🏻‍♂️ should test with test builds before i write issues...

**Comment by MysticJay** [comment]
@MaxEtMoritz NP, that is what "Issues" is for.
