### ISSUE TITLE
bug when used with HPWU conversion

### ISSUE THREAD

**Issue by Nseraf** [IITC-CE/ingress-intel-total-conversion#413]
Hello, Im not sure if this has been mentioned before but when using this script to convert intel.ingress with ittc hpwu it causes intel to stop loading portals. I've tried deleting mapped portals and disabling hpwu tools/ittc plugin but it doesn't help. When I disable the "This is hpwu!" option all portals load again and the attached image's errors vanish. This started happening last week after intel's latest page update.  Thanks for all the great work put in this script!
![Capture](https://user-images.githubusercontent.com/33002317/102024853-0e0fac00-3d9d-11eb-8ff3-93dde1435253.PNG)

**Comment by MysticJay** [comment]
@Nseraf Maybe you should ask someone who developed that plugin. Neither the ingress intel map, nor IITC are designed for HPWU, nor will be cared about plugins not designed for Ingress.

**Comment by McBen** [comment]
related to: https://github.com/IITC-CE/ingress-intel-total-conversion/issues/410
you have to enable "Ornaments"  (thats mean you've to disable 'this is hpwu' and manuall choose your layers)
or use the test-build.

**Comment by McBen** [comment]
here a quickly hacked bug workaround plugin:
https://pastebin.com/5NXVynw3

**Comment by Nseraf** [comment]
okay, many thanks!
