### ISSUE TITLE
Popup: 'Cross-Links' requires 'draw-tools'

### ISSUE THREAD

**Issue by jbreazeale** [IITC-CE/ingress-intel-total-conversion#448]
At times when Chrome restarts and IITC restarts with it, I get a pop-up containing the message:

'Cross-Links' requires 'draw-tools'

Under the same circumstance the Map Tile changed from OpenStreetMap before the restart, to CartoDB Dark Matter after the restart.

Checking Tampermonkey I see I have **IITC plugin: Cross links** v1.3.0 and **IITC plugin: Draw tools** v0.8.0.

See the attached files for the pop-up text and plugin versions.

![image](https://user-images.githubusercontent.com/2078057/109436720-7bb79580-79e6-11eb-9615-b7799c2de86b.png)
![image](https://user-images.githubusercontent.com/2078057/109436723-83773a00-79e6-11eb-8c4f-87e11c2e91ef.png)

**Comment by jbreazeale** [comment]
Is the message a bug or a feature?

**Comment by MysticJay** [comment]
@jbreazeale What IITC version (from "about iitc") are you using?

**Comment by MysticJay** [comment]
@MysticJay Versions seem ok
what do you have in console?
try loading drawtools before crosslinks (although that should not matter)

**Comment by jbreazeale** [comment]
It looks like I'm using version 0.31.1.

![image](https://user-images.githubusercontent.com/2078057/109437498-a9064280-79ea-11eb-819a-a63544358f03.png)

**Comment by jbreazeale** [comment]
> what do you have in console?

![image](https://user-images.githubusercontent.com/2078057/109437598-36e22d80-79eb-11eb-88d9-fcb47bfd720a.png)

**Comment by jbreazeale** [comment]
> try loading drawtools before crosslinks (although that should not matter)

I am a bit of a newbie on that level of ability.  I'll need some detailed instructions.  Reproducing this issue is a bit of a challenge, it seems to only happen when Chrome is updated.  When I create a new tab and load IITC in that tab there is no popup.

**Comment by jbreazeale** [comment]
Just so you see the popup and map tile at the same time, see the attached screen shot.

![image](https://user-images.githubusercontent.com/2078057/109437693-d56e8e80-79eb-11eb-8442-ec0b5ac1ca4e.png)

**Comment by le-jeu** [comment]
Can you reproduce with only cross-link/draw-tools/osm enabled ? (in TMonkey)
If no, try enabling the other scripts one by one.

> I am a bit of a newbie on that level of ability. I'll need some detailed instructions. Reproducing this issue is a bit of a challenge, it seems to only happen when Chrome is updated. When I create a new tab and load IITC in that tab there is no popup.

See the numbering in TamperMonkey, that's the load order for TM. It might play a role (but it shouldn't in this case).

In the console, look for message you don't see on a working iitc setup. (some are unavoidable)
