### ISSUE TITLE
Fly links not working

### ISSUE THREAD

**Issue by Ren-Noir** [IITC-CE/ingress-intel-total-conversion#450]
I have never had an issue like this. For the life of me, I cannot get fly links to work for. Ivload and reload plugins, force update, but nothing seems to work. Please help

**Comment by MysticJay** [comment]
@Ren-Noir do you have an active draw?

**Comment by le-jeu** [comment]
since last release, you need to draw at least one polygon to include all the portals you want to field with.
https://github.com/IITC-CE/ingress-intel-total-conversion/pull/310#issue-362714616

>   - region selection with the polygon draw tool
>   - exclusion of portals with the marker draw tool
>   - steady drawing (portals is not excluded from the drawing if they are moved out of boundaries)

![image](https://user-images.githubusercontent.com/64744459/110257699-57882580-7f9f-11eb-806f-519b4d3a7770.png)

**Comment by johnd0e** [comment]
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/2daad393c75f45e9f121136c4717d4dec51fca4f/plugins/fly-links.js#L344

I see that plugin now silently breaks if draw-tools is not available.
That is not good at all.
Perhaps better solution would be fallback to map bounds.

@Fly33

**Comment by johnd0e** [comment]
Another bug: fly-links does not react on drawing. So we have to pan slightly to initiate fly-links update.
Annoying.

**Comment by johnd0e** [comment]
Also: I'd like to use Circle too, not only Polyline.

**Comment by crystalwizard** [comment]
Might consider a popup if there's no polygon to inform the user that a polygon must be drawn before flylinks can activate
