### ISSUE TITLE
plugins [Fix maps offsets in China] doesn't work

### ISSUE THREAD

**Issue by Konano** [IITC-CE/ingress-intel-total-conversion#488]

**Comment by johnd0e** [comment]
Please provide steps to reproduce the issue.
- map permalink
- what do you expect to see there
- what do you see instead

**Comment by Konano** [comment]
Link: https://intel.ingress.com/?ll=39.998139,116.32425&z=16

These two maps have positional deviations in China. In Google Roads, the location of the road is wrong.

Google Roads:
![image](https://user-images.githubusercontent.com/22500116/115535123-0d4ad180-a2cb-11eb-8f9f-48113bc4b0cd.png)

Google Satellite:
![image](https://user-images.githubusercontent.com/22500116/115535205-1e93de00-a2cb-11eb-8150-1c64c4b5327b.png)

Plugins:
![image](https://user-images.githubusercontent.com/22500116/115535249-26538280-a2cb-11eb-947a-4955c4daca94.png)
![image](https://user-images.githubusercontent.com/22500116/115535274-2bb0cd00-a2cb-11eb-8475-84f690c28609.png)

**Comment by johnd0e** [comment]
@Konano Confirmed.
Here is better link: https://intel.ingress.com/?ll=40.007935,116.304788&z=16

**Comment by johnd0e** [comment]
Fixed version:
[fix-china-map-offset.user.js.md](https://github.com/IITC-CE/ingress-intel-total-conversion/files/6350187/fix-china-map-offset.user.js.md)
