### ISSUE TITLE
Highlight script from external not working

### ISSUE THREAD

**Issue by max246** [IITC-CE/ingress-intel-total-conversion#493]
Creating a bespoke highlight script and then loading as external script is not adding itself to the dropdown.

Only the current installed plugin are visible, and even if you download the same script from the source code, load it as external, it does not show up in the list.

There is something that is not making the "setup" function be to called when the script is loaded externally.

To replicate the issue, just download any highlight and load it as external, here an example https://github.com/iitc-project/ingress-intel-total-conversion/blob/a34df32640fbec85a245198451e0d5141c711927/plugins/portal-highlighter-level-color.user.js

**Comment by McBen** [comment]
You cannot use the source-code directly.
The `@@...@@` markers are placeholders. You've to run `build.py local`to transform/compile the code.

Your example will be converted to this:
https://static.iitc.me/build/release/plugins/portal-highlighter-portals-my-level.user.js

**Comment by MysticJay** [comment]
@max246 That script is not maintained, thus not supporting the new intel URL.

you will nedd to edit it yourself:
remove all match and include headers, then only add one
// @match https:intel.ingress.com/*

BUT: this special script is available from inside IITC-ce and also from iitc.app ready to use.

**Comment by max246** [comment]
> You cannot use the source-code directly.
> The `@@...@@` markers are placeholders. You've to run `build.py local`to transform/compile the code.
> 
> Your example will be converted to this:
> https://static.iitc.me/build/release/plugins/portal-highlighter-portals-my-level.user.js

ok this worked, thnanks!
