### ISSUE TITLE
Portal view: background should not be transparent

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#5]
It was opaque before, I suppose the problem appeared after one of last commit, probably related to #3. 

Actually, I already saw the same in McBen's fork.

**Comment by modos189** [comment]
Not watching this. Maybe cleaning the app data or reinstalling it will help?

**Comment by johnd0e** [comment]
It is actually clean install.
Looks like this:
![screenshot_2018_12_02_18_12_19_227_org](https://user-images.githubusercontent.com/1838643/49359228-365c6e80-f6de-11e8-88fb-20582898a900.png)

**Comment by johnd0e** [comment]
It depends on map tiles set.
Try Google Roads / Default Ingress / Satellite / Gybrid / Terrain

**Comment by modos189** [comment]
Yeap, caught it
