### ISSUE TITLE
draw tools getting deactivated on reload

### ISSUE THREAD

**Issue by t40** [IITC-CE/ingress-intel-total-conversion#509]
The draw tools plugin gets deactivated on every reload of the browser window.

**Comment by MysticJay** [comment]
Please provide details on 
Browser and for the portalMenu the "about IITC"

**Comment by t40** [comment]
I use Google Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)

IITC
Version: 0.31.1 [release]
Plugins:
Force Zoom Level - 0.1.1.20170527.40451
Highlight portals missing resonators - 0.1.2
Live Inventory - 0.0.12
Localized scoreboard - 0.3.0

**Comment by McBen** [comment]
do you use IITC-Button? or Tampermonkey?

**Comment by MysticJay** [comment]
@t40 What DrawTools Version?

**Comment by t40** [comment]
The logic doesn't make sense to me, but I was logged out of my Google account on Chrome. Since I logged back in, it works.
IITC-Button, DrawTools 0.8.0
