### ISSUE TITLE
Plugins are not listed in About-IITC Dialog

### ISSUE THREAD

**Issue by McBen** [IITC-CE/ingress-intel-total-conversion#513]
If the main script is loaded first it may execute it's boot-routine before other scripts have finished loading.
This leads to an incomplete `bootPlugins.info` array (some items are still left in the `bootPlugins` array).

Tested on FF with TM, installed IITC-main first, then a ~12 other plugins.
On first start only one plugin was listed in the about dialog. On a second run it lists 6.
works fine if main script is loaded last

NOTE: since `bootPlugins` is an array `bootPlugins.info` should be moved to another variable

**Comment by johnd0e** [comment]
@McBen
Have the the issue get more severe after #485?
Could you check?

**Comment by McBen** [comment]
yes, reverting #485 helps a lot.  The extra setTimeout of 073f7eb is looking good too.

Atleast I wasn't able to reproduce this issue on current system.
But it's hard to tell if this is a real fix. Can't say if caching, system timing or weather condition is involved too.
(even with the old code the plugin list were growing after multiple reloads)

**Comment by johnd0e** [comment]
> But it's hard to tell if this is a real fix.

Sure it is not ultimate fix.
I suppose we should re-inspect `bootPlugins` every time before About-window is opened.

**Comment by McBen** [comment]
> I suppose we should re-inspect `bootPlugins` every time before About-window is opened.

hidden in PR #514
https://github.com/IITC-CE/ingress-intel-total-conversion/pull/514/commits/635a77bfc8dba8379343a0e026ac76a77706c913 :)
