### ISSUE TITLE
[ERROR] console error.

### ISSUE THREAD

**Issue by lshaf** [IITC-CE/ingress-intel-total-conversion#515]
As for my observation, removing
div#header > div#nav causing problem below after dragging map.
![image](https://user-images.githubusercontent.com/4636265/123737275-dd243e00-d8cc-11eb-8855-944f1c4ad72f.png)

so when I add it manually before dragging map, like below.
```
<div id="header">
  <div id="nav"></div>
</div>
```

error is gone.

**Comment by johnd0e** [comment]
Please check if it is fixed in latest test build

**Comment by lshaf** [comment]
It's fixed
