### ISSUE TITLE
Scale Bar plugin does not always show up (Firefox, Tampermonkey)

### ISSUE THREAD

**Issue by Thomas-Cee** [IITC-CE/ingress-intel-total-conversion#518]
Here is a video of it happening.
https://youtu.be/QobI20zVWBo

Let me know if I can help in any way with more info. 

Using Firefox, and Tampermonkey.

**Comment by johnd0e** [comment]
What is in debug console?

**Comment by johnd0e** [comment]
Please check if it is fixed in latest test build
