### ISSUE TITLE
please remove this issue

### ISSUE THREAD

**Issue by poolerMF** [IITC-CE/ingress-intel-total-conversion#535]
please remove this issue

**Comment by johnd0e** [comment]
@poolerMF 
What about stock intel? Do you see different order there?

**Comment by McBen** [comment]
it's random on stock intel too:
![grafik](https://user-images.githubusercontent.com/29117/140931452-e0e1b5d8-349e-419f-a02c-9ab4fea602f3.png)

But what is the "logical order" ?  There are arguments for both orders.
IMHO the first is more readable.

**Comment by poolerMF** [comment]
please remove this issue
