### ISSUE TITLE
Include pnpoly utility

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#552]
Seen in `fix-china-map-offset`, `layer-count`, `fly-links`

Sources:
- https://github.com/substack/point-in-polygon
- https://github.com/mikolalysenko/robust-point-in-polygon
- https://github.com/rowanwins/point-in-polygon-hao
- https://github.com/metafloor/pointinpoly
- ... https://github.com/topics/point-in-polygon

Ref: https://github.com/IITC-CE/ingress-intel-total-conversion/pull/65#issuecomment-455151352

**Comment by le-jeu** [comment]
so this is now done in 97293922a16943d86d3b8b989a615ddb3cd57b27

**Comment by Artoria2e5** [comment]
hmm, pretty sure it can be closed -- now that it's moved to global. happy to see my translation of pnpoly get used still. it's the old 1973 code, not one of the new "robust" ones, but... uhhh, i don't think we will be dealing with weirdly large numbers with lat and lngs.

one day we might need to "expand" long polygon vertices into more points on a great-circle approximation, but that day is not today.
