### ISSUE TITLE
exception in  window.setupPlayerStat causing no passcode reward dialog

### ISSUE THREAD

**Issue by jim0watters** [IITC-CE/ingress-intel-total-conversion#589]
There is a bug in IITC subroutine window.setupPlayerStat that throws an error that is noticed when trying to redeem passcodes. 
The passcode is redeemed but no message of the reward is displayed. 
I am avoiding this bug by commenting out the lines 24847 to 24850

```
 // if(data.playerData) {
 //   window.PLAYER = data.playerData;
 //   window.setupPlayerStat();
 // }.
```

I have not figured out what is wrong inside of setupPlayerStat. 

I added the work around a few months ago and forgot about it until another Agent was complaining about the same issue of no dialog of passcode rewards. I have reenabled the code and will try to remember to add a breakpoint before putting in my next passcode.

**Comment by le-jeu** [comment]
isn't this fixed by #559 in 0.33.0 ?

**Comment by jim0watters** [comment]
Don't have any passcodes to test and been a while since I saw the exact exception, but that looks like the same issue. Thank you.

**Comment by xscreach** [comment]
I've been redeeming some codes on versions 0.33.0-0.35.0 and all displayed the passcode content.

Imho this issue can be closed

**Comment by jim0watters** [comment]
Issue has been fixed. Redeeming codes since 0.33.0 has not been a problem.
