### ISSUE TITLE
Move and zoom to portal

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#6]
Regarding this patch: https://github.com/IITC-CE/ingress-intel-total-conversion/commit/59cc3126bd85f5c9e298e94517384b34c8458d65

1. I am unable to see any icon (developer build).
   Perhaps there is some problem with svg rendering.
   Tried with different values of "Use Canvas rendering" option (btw McBen's fork does not have this 
   option anymore)
2. When I click on empty space at left of the title - map actually moves and zooms, but user cannot see it 
   until he closes portal view .
   Imho it would be more intuitive if porlal view gets closed automatically.

**Comment by modos189** [comment]
I suspect that I need to enable svg support when building your application. But I am not sure that this button is needed in the mobile version of IITC

By the way, I also want to use canvas by default, because I always turn it on, it works faster.

**Comment by johnd0e** [comment]
> But I am not sure that this button is needed in the mobile version of IITC

It is needed because there are **really many many cases** when we can open info for portal that is not in current view.

**Comment by johnd0e** [comment]
What can you tell about 2nd point:
> When I click on empty space at left of the title - map actually moves and zooms, but user cannot see it
until he closes portal view .
Imho it would be more intuitive if portal view gets closed automatically.

Any chances to fix it?
