### ISSUE TITLE
Android App crashing in versions 0.33.0 and 0.34.0

### ISSUE THREAD

**Issue by wbwue** [IITC-CE/ingress-intel-total-conversion#600]
**What is expected to happen:**
App starts regularly and will ask for login.

**What happens:**
On first start, permission for Location is requested. White screen for a second, then IITC logo appears for a second, then App is closed.

**Versions affected:**
0.34.0 (F-Droid store, iitc repo)
0.33.0 (F-Droid store, f-droid repo)

**System information**
System: Android 9 (LineageOS 16.0)
Phone: Motorola z2 play
rooted device

**Crash logs**
<details><summary>same for both versions</summary>

recorded with `adb logcat --buffer=crash`
```
11-18 10:36:21.306  5412  5412 E AndroidRuntime: FATAL EXCEPTION: main
11-18 10:36:21.306  5412  5412 E AndroidRuntime: Process: org.exarhteam.iitc_mobile, PID: 5412
11-18 10:36:21.306  5412  5412 E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x7f0d00b5
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:348)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.content.Context.getText(Context.java:574)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.widget.SearchView.getQueryHint(SearchView.java:622)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.widget.SearchView.n(SearchView.java:1102)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.widget.SearchView.setSearchableInfo(SearchView.java:409)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at org.exarhteam.iitc_mobile.IITC_Mobile.onCreateOptionsMenu(IITC_Mobile.java:674)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.fragment.app.d.onCreatePanelMenu(FragmentActivity.java:325)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:94)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.app.h$d.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:94)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at androidx.appcompat.app.k$1.run(ToolbarActionBar.java:1455)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-18 10:36:21.306  5412  5412 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**What else did I try**
Version 0.32.1 from F-Droid works
Disabled AdAway, still crashing.

**Comment by modos189** [comment]
Please try https://github.com/IITC-CE/website/raw/master/static/build/artifact/PR601/IITC_Mobile-test.apk

**Comment by wbwue** [comment]
> Please try https://github.com/IITC-CE/website/raw/master/static/build/artifact/PR601/IITC_Mobile-test.apk

@modos189 works with the test version. Could setup and also tested adding some plugins. Could also reopen it (had to use a intel link, as from launcher it said 'App not found')

**Comment by modos189** [comment]
@wbwue It is possible that the error is related to proguard. Do you have other test builds working? The test builds have proguard disabled. Try new build https://github.com/IITC-CE/website/raw/master/static/build/artifact/PR601/IITC_Mobile-test.apk

**Comment by wbwue** [comment]
This version works as well, though I haven't tried with empty app data yet. Does it make a difference?

**Comment by modos189** [comment]
@wbwue Great! Now please check that the beta versions work as well (proguard on, respectively) https://github.com/modos189/website/raw/master/static/build/beta_archive/2022-12-02_10-59/IITC_Mobile-beta.apk

**Comment by wbwue** [comment]
@modos189 Yes, that works as well.
