### ISSUE TITLE
can not be rendering intel's links, portal icons and so on

### ISSUE THREAD

**Issue by swan73** [IITC-CE/ingress-intel-total-conversion#605]
Hi, guys

I had made updating chrome to 108.0.5359.94. After updating, it could not be rendering intel's orginal source on map with IITC.
So I tried revising chrome from now one to old one "107.0.5304.110". But it can not worked well as well.

my environment is as below :
MacOS 13.0.1（22A400）
Chrome 107.0.5304.110 and 108.0.5359.94

Do you gyus have same problem as same as I have?

**Comment by modos189** [comment]
What userscript manager do you use?

**Comment by swan73** [comment]
Hi modos189,

> What userscript manager do you use?

I am not sure how dose it work.
But it is running with Tampermonkey.

**Comment by modos189** [comment]
I tested running on MacOS 12.6.1, Chrome 108.0.5359.94, TamperMonkey 4.18.1 and IITC-CE 0.34.0.
Everything works fine, I don't see any of the bugs you encountered.
Open the developer panel and switch to the Console tab. There will probably be error information there. Send it here if there is one.

**Comment by le-jeu** [comment]
may be related https://github.com/chromium/chromium/commit/83749a108ea01b38449741bf728fee4289824f0b

**Comment by swan73** [comment]
Hi all,
It had not been any error information on console.
I tried refreshing all extensions and re-installing them on chrome.
It worked well so far.

Thanks for all your help and advice.
Closed this issue.
