### ISSUE TITLE
(Plugin-Ingress scoring regions) Region-name search results show wrong sub-cell

### ISSUE THREAD

**Issue by McBen** [IITC-CE/ingress-intel-total-conversion#622]
The plugin Ingress scoring regions not only add the region grid it also alows to search for region names.  
But sometime when searching for a cell the last number is wrong.

Example:
Searching for `NR02-echo-08` resulted in `NR02-echo-02`
and vice versa: searching for `NR02-echo-02` resulted in `NR02-echo-08`

**Comment by xscreach** [comment]
Fixed with #623

**Comment by modos189** [comment]
fixed https://github.com/IITC-CE/ingress-intel-total-conversion/pull/623
