### ISSUE TITLE
Alphabetical sorting of all plugin links under the portal details panel

### ISSUE THREAD

**Issue by mxxcon** [IITC-CE/ingress-intel-total-conversion#631]
I propose that IITC automatically sort all the links/buttons under the portal details panel in alphabetical order. This would be a helpful improvement for usability.

It would make it easier to find the plugin buttons you need. Currently, their order is not fixed, so it can be difficult to find the one you're looking for, especially if you have a lot of plugins installed. Sorting that list alphabetically would make them much easier to find.

It would prevent the links from getting reshuffled if you add or remove plugins. Currently, if you add or remove a plugin, the order of the links can change. This can be frustrating, especially if you've got used to their order/position. Sorting alphabetically would prevent this from happening.

I imagine the code to sort the links alphabetically should be relatively short and simple.

**Comment by le-jeu** [comment]
Since the plugins add a link themselves into the toolbox at DOM level, iitc would need to watch any change to place any new link at the correct position.
It would be nice to expose an API for this but old plugins won't use it anyway.

**Comment by MysticJay** [comment]
usually changes to the toolbox are only done during setup. So it should be sufficent to sort once after all plugins got initialized

**Comment by Heistergand** [comment]
I propose to add an option (additionally to the alphabetical sorting, which would be the default) to let the user sort the buttons like they want to by dragging them around, maybe in a popup list - or what about the "About IITC" dialog?

**Comment by nexushoratio** [comment]
Could an admin update the issue title to reflect the "allow user to order toolbox buttons" feature request?  As titled, I think this is complete.  (or alternative, a new issue)

**Comment by mxxcon** [comment]
> As titled, I think this is complete. (or alternative, a new issue)

How is this complete? This functionality still doesn't exist

**Comment by Jormund** [comment]
@mxxcon currently buttons are alphabetically sorted. (tested just now in 0.38.0)![Screenshot_2024-06-05-18-33-08-58_4bd081dab89a3c82e75a2ae7696e5187.jpg](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/5835191/029fd0df-9c4a-4356-a3df-5e0be8e647ef)

**Comment by nexushoratio** [comment]
> How is this complete? This functionality still doesn't exist

Links in the toolbox are alphabetical, regardless of the order plugins are loaded.  At least for the plugins I regularly use.

It looks to be implemented with https://github.com/IITC-CE/ingress-intel-total-conversion/blob/199c9f7bdc0acb79db3855f9f5cd7c0cd516ec66/core/code/toolbox.js#L147

Are you seeing otherwise?

**Comment by mxxcon** [comment]
🤔 I remember it was added in one version but then disabled in another due to some issues. I've been running my own sorting plugin so didn't notice any difference. 

But I guess since it's there this issue can be closed as fixed. 👍

**Comment by nexushoratio** [comment]
I was surprised one day when I noticed they were sorted!
