### ISSUE TITLE
Access blocked: authorisation error [Sync Error]

### ISSUE THREAD

**Issue by DineshValor** [IITC-CE/ingress-intel-total-conversion#657]
Getting error pop screen while Sync Authorization.
![Screenshot_2023-08-02-09-52-11-74_4bd081dab89a3c82e75a2ae7696e5187](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/98645523/c2f2dfe5-57fd-4f49-8ac2-422c9970a160)

**Comment by le-jeu** [comment]
When do you get this error ? On intel login ? Login for Sync (guessing from the title change)?

Can you test against the beta build ? 
https://iitc.app/build/beta/IITC_Mobile-beta.apk

**Comment by DineshValor** [comment]
> When do you get this error ? On intel login ? Login for Sync (guessing from the title change)?
> 
> Can you test against the beta build ? https://iitc.app/build/beta/IITC_Mobile-beta.apk

Yep Sync error, and gonna try with beta apk.

**Comment by DineshValor** [comment]
> When do you get this error ? On intel login ? Login for Sync (guessing from the title change)?
> 
> Can you test against the beta build ? https://iitc.app/build/beta/IITC_Mobile-beta.apk

Got error while login in IITC-CE beta apk too.
![Screenshot_2023-08-02-13-47-23-73_679f2a4e465a16c5fd208cf574d14675](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/98645523/99c38a95-4119-4966-ae93-83cea25ab7ed)

**Comment by le-jeu** [comment]
A simple solution would be to enable the `Fake User Agent` setting from the Advanced setting. 
But you may try first to enable the popup setting.

Since I'm not able to reproduce the bug, It would nice if you can try to enable the debug console and have a look into the message there (this is not about the plugin, but from the advanced settings > Configure IITC Menu > :heavy_check_mark: Debug, then from the main view in the menu, enable Debug, then you switch between intel and debug console with left bottom button.)

**Comment by DineshValor** [comment]
> A simple solution would be to enable the `Fake User Agent` setting from the Advanced setting. But you may try first to enable the popup setting.
> 
> Since I'm not able to reproduce the bug, It would nice if you can try to enable the debug console and have a look into the message there (this is not about the plugin, but from the advanced settings > Configure IITC Menu > ✔️ Debug, then from the main view in the menu, enable Debug, then you switch between intel and debug console with left bottom button.)

To reproduce the Sync/Login error window:-
=> Enable `Fake User Agent` and restart apk then disable it and again restart.
=> Try to login or authenticate Sync login.

After Popup setting enable:
![Screenshot_2023-08-02-16-16-29-73_4bd081dab89a3c82e75a2ae7696e5187](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/98645523/9d0db989-e0e0-42da-ae73-9fdcc8bd272f)

After `Fake User Agent` setting enabled issue solved but it's comes again after disable it.

Thanks for the tip. For now using it with Fake User agent option enable.

**Comment by MysticJay** [comment]
Please check if 0.36.1 resolves the issue.

**Comment by Mandrex16** [comment]
Thx to someone!!! Update hit today!
Cheers!!!
![Screenshot_20230821_211137_IITC Mobile Beta](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/102683187/1d728e34-c378-459d-9064-91a938ad9cc4)

**Comment by DineshValor** [comment]
> Please check if 0.36.1 resolves the issue.

Thanx, issue resolved in update 0.36.1.
