### ISSUE TITLE
Attribution in About dialog

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#67]
@modos189 
Why have you removed attribution info from iitc `About` dialog?
9fe3e94cabc5da5eccaa2ab1dbd57a0039e99ac9

**Comment by johnd0e** [comment]
taphold.js: marked as unknow licence, but it's not true: 
[LICENSE](https://github.com/richadams/jquery-taphold/blob/master/LICENSE)

Todo: make all links point right to licence info.

**Comment by johnd0e** [comment]
@modos189 
BTW, why have you removed attribution info from iitc About dialog?

**Comment by johnd0e** [comment]
Attribution itself should be updated #91.

**Comment by modos189** [comment]
> Why have you removed attribution info from iitc About dialog?

What is it for? I think users are not at all interested. Information remains in the github repository.

**Comment by johnd0e** [comment]
Ok then.
