### ISSUE TITLE
Wrong region naming (and probably indexing) in the AS face

### ISSUE THREAD

**Issue by davidxuang** [IITC-CE/ingress-intel-total-conversion#678]
IITC currently gives such naming scheme for AS regions:
```
S1 . . . S16
.
.
.
A1
```
but the actual names given by Niantic are:
```
S16 . . . A16
.
.
.
S1
```
I'm guessing that it could be a problem imported from the S2 library, probably [line 74](https://github.com/jonatkins/s2-geometry-javascript/blob/27d91107450fbdb5f600d7f9a576da1ca31b77f2/src/s2geometry.js#L74) and [line 106](https://github.com/jonatkins/s2-geometry-javascript/blob/27d91107450fbdb5f600d7f9a576da1ca31b77f2/src/s2geometry.js#L106).

**Comment by Breenzy** [comment]
![image](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/30122226/bbec4e8f-8059-4498-b59c-d8db399ca452)
Can confirm this issue.

**Comment by McBen** [comment]
Looks like nia swap id and codename (i,j) for odd faces.
ex:  PA**03-Mike**15 <=> PA**12-Charlie**15   (03=Charlie, 12=Mike)

Quick fix could be:
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/20f996d2e931d1e74a5dec280be120a7d13ffbc4/plugins/regions.js#L70
```
if (cell.face & 1) {
        [regionI,regionJ] = [regionJ,regionI];
}
```

(+ some similar in search)
