### ISSUE TITLE
Cell Score Names Wrong on Map

### ISSUE THREAD

**Issue by aaronvianno** [IITC-CE/ingress-intel-total-conversion#698]
The default built in plugin to display cell names on the map, shows the wrong cell names. Osm maptile in use if you want to recreate the bug. 
![Screenshot_2024-02-05-13-18-25-19_4bd081dab89a3c82e75a2ae7696e5187](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/9960737/4db40c8b-b05f-4763-885b-678ac16f9da6)

**Comment by le-jeu** [comment]
fixed with #697 
please try with [IITC Mobile Beta](https://iitc.app/build/beta/IITC_Mobile-beta.apk) to confirm
