### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by mangofire263** [IITC-CE/ingress-intel-total-conversion#700]
I have latest version of iitc mobile, but when I login either Google or Facebook, it reverts to old intel map.
Is there a work around?
Phone a13 samsung

**Comment by modos189** [comment]
Do you have version 0.37.2?
You can download it here https://iitc.app/download_mobile

**Comment by mangofire263** [comment]
Yes I have newest version

**Comment by modos189** [comment]
1. Go to Settings -> Debug info. Show this 

2. Go to Settings -> Advanced settings -> Customize IITCm menu. Check the Debug checkbox there. Then go back and log in via Google. When you have Intel open, go back to the app, tap the three dots at the top (where Settings is) and tap Debug. Show a screenshot of this debug window

**Comment by mangofire263** [comment]
The iitc app will not open by default it goes immediately to standard intel
map

**Comment by mangofire263** [comment]
Belay that

**Comment by mangofire263** [comment]
Here's screenshots of settings

**Comment by modos189** [comment]
The screenshot is not attached

**Comment by mangofire263** [comment]
I will resend it.

**Comment by nesehehame** [comment]
Hello, I have the same problem since yesterday 
![Screenshot_20240218_075829_IITC Mobile](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/160380372/2fe545f2-b99d-4148-837f-c2da96a2fecf)

**Comment by modos189** [comment]
Install the latest version IITC Mobile (currently 0.37.2)
https://iitc.app

**Comment by nesehehame** [comment]
I thought I did, but apparently not. It's working now, thanks.
