### ISSUE TITLE
Draw Tools update from 0.10.1 to 0.10.2 - menu is lost

### ISSUE THREAD

**Issue by drmuttik** [IITC-CE/ingress-intel-total-conversion#708]
After Draw Tools updat to 0.10.2 it lost the menu item (on the right side beneath the portal info; that menu item is used for copying and pasting the drawn items like links and polylines). The drawing buttons on the left side still work. Everything was fine in 0.10.1 before the update. Restating Tampermonkey and/or Draw Tools does not solve the problem. Updating Tampermonkey from 4.19.6183 to 5.0.1 also does not help.

**Comment by McBen** [comment]
Make sure you also updated the main iirc script to v0.38.0+

**Comment by drmuttik** [comment]
OK with IITC 0.38.0

**Comment by drmuttik** [comment]
Possibly a problem with only a specific combination of versions (Tampermonkey+IITC+DrawTools)
