### ISSUE TITLE
Filtering portals by level doesn't work for Machina

### ISSUE THREAD

**Issue by dementedtulip** [IITC-CE/ingress-intel-total-conversion#712]
Unchecking the filter toggles for Level 1 Portals, Level 2 Portals, etc. doesn't work for Machina portals. For example, if I uncheck 'Level 1 Portals', all the level 1 RES and ENL portals disappear, but the Machina portals stay visible. Attached are two images. One shows that Machina portals are still visible despite all filters being unchecked. The other is a line of code I think needs to be added, but I'm not a pro, so I will leave it to you guys. :D

![photo_2024-02-29_21-27-30](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/161793519/0c80b9fe-50cf-4c7f-ab61-23d570397f8c)

![photo_2024-02-29_21-27-44](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/161793519/58364ee1-d882-4774-8bf1-9d3988f1875b)

**Comment by dementedtulip** [comment]
Opened PR 713 for this

**Comment by nexushoratio** [comment]
I think this issue can be marked as fixed now.
