### ISSUE TITLE
SVG icons for plugins

### ISSUE THREAD

**Issue by Artoria2e5** [IITC-CE/ingress-intel-total-conversion#736]
The current `@icon` value injected during build are all PNGs. It could be a good idea to replace them with minified SVG files where that makes sense.

I noticed that the icons are a little blurry when I finally added an icon to my plugin:

![image](https://github.com/IITC-CE/ingress-intel-total-conversion/assets/6459309/0414e3ec-065f-4112-ac83-21b35d85390f)

My plugin's icon stands out among all the rest because it's an SVG. Maybe we can move some official plugins to SVG too? For what is worth, the SVG is 1.7 kb -- not that different from the PNGs in https://iitc.app/extras/plugin-icons/, and even smaller than them if you gzip.

(My icon also stands out because it doesn't have the right black border and corners, but that, too, can be solved when we have official SVGs.)

* * *
"where that makes sense" is because we have some icons that aren't drawn by us, like the basemap icons.

**Comment by Artoria2e5** [comment]
Alright, first issue with this: my script's `@icon` is not showing up in Tampermonkey. This of course won't affect whatever I want to do to IITC Button, but it's annoying and I want to know why: does Tampermonkey not understand SVG (unlikely: https://github.com/Tampermonkey/tampermonkey/issues/1500 works), or did it get confused by GitHub's awful Content-Type?

Yep, works with jsdelivr. Is content-type issue, won't happen with your iitc.app server.

**Comment by modos189** [comment]
I originally chose the png format for the icons because svg images look more blurry than png at low resolution. But as it turned out, to simplify further support of icons and instead of duplicating 32px and 64px icons, it is more convenient to use svg. Besides, IITC Button uses 24px icon size, which makes png icons look blurry.

I will prepare a new set of svg icons, or maybe you want to do it =)

**Comment by modos189** [comment]
I have prepared svg icons, new IITC resets will have vector icons https://github.com/IITC-CE/website/pull/55
