### ISSUE TITLE
Stuck before signing in

### ISSUE THREAD

**Issue by HankChow** [IITC-CE/ingress-intel-total-conversion#752]
![Screenshot_2024-08-05-10-24-24-681_org.exarhteam.iitc_mobile-edit.jpg](https://github.com/user-attachments/assets/f2a5c122-eaf2-4b32-a5b0-387428639af4)

The app is stuck at this screen forever, even with many times of reloading the page or restarting the app. My network is good, I can use the intel map in webpage without any issue. 

Here is my debug info:
Manufacturer: Xiaomi
Model: 22041216C
Android version: 34
Android version release: 14
IITC Mobile version: 0.38.1 (release)
IITC Version: 0.38.1
System User Agent: Mozilla/5.0 (Linux; Android 14; 22041216C Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36
Default IITC User Agent: Mozilla/5.0 (Linux; Android 14; 22041216C Build/UP1A.231005.007) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36
Fake user agent: disabled
Active user plugins: 0

**Comment by xscreach** [comment]
Niantic had some problems with servers this night (about 10 hours ago). Ingress lagged more than usually, other games were affected aswell, and iitc in this way too.

This might also happen when your internet connection interrupts or smth. This was the case of niantic servers though. 
It should be all ok by now... right?

**Comment by HankChow** [comment]
> Niantic had some problems with servers this night (about 10 hours ago). Ingress lagged more than usually, other games were affected aswell, and iitc in this way too.
> 
> This might also happen when your internet connection interrupts or smth. This was the case of niantic servers though. 
> It should be all ok by now... right?

@xscreach Unfortunately, no. I downloaded IITC about one week ago and it keeps stuck every time. So I think it's not caused by the temporary server issue you mentioned.

**Comment by xscreach** [comment]
> > Niantic had some problems with servers this night (about 10 hours ago). Ingress lagged more than usually, other games were affected aswell, and iitc in this way too.
> > 
> > This might also happen when your internet connection interrupts or smth. This was the case of niantic servers though. 
> > It should be all ok by now... right?
> 
> @xscreach Unfortunately, no. I downloaded IITC about one week ago and it keeps stuck every time. So I think it's not caused by the temporary server issue you mentioned. 

Oh, ok, sorry.

In that case try turning the fake user agent on (Settings -> Advanced -> Fake user agent - check)

But id say it's some kind of xiaomi setting for webview not to run javascript. 

If the fake agent doesn't help, maybe you can come to discuss the issue faster here - https://t.me/+1xncfR_TV3BjZTIy ?

**Comment by HankChow** [comment]
> > > Niantic had some problems with servers this night (about 10 hours ago). Ingress lagged more than usually, other games were affected aswell, and iitc in this way too.
> > > 
> > > This might also happen when your internet connection interrupts or smth. This was the case of niantic servers though. 
> > > It should be all ok by now... right?
> > 
> > @xscreach Unfortunately, no. I downloaded IITC about one week ago and it keeps stuck every time. So I think it's not caused by the temporary server issue you mentioned. 
> 
> Oh, ok, sorry.
> 
> In that case try turning the fake user agent on (Settings -> Advanced -> Fake user agent - check)
> 
> But id say it's some kind of xiaomi setting for webview not to run javascript. 
> 
> If the fake agent doesn't help, maybe you can come to discuss the issue faster here - https://t.me/+1xncfR_TV3BjZTIy ?

@xscreach Thanks for the work around. I've tried enabling the fake user agent. It randomly works but still needs about a minute's waiting (not very tolerable but better than before...). And it comes to another issue. It gets stuck again after my clicking "Sign in with Google" even I've waited for several minutes.
![Screenshot_2024-08-11-09-33-36-974_org.exarhteam.iitc_mobile-edit.jpg](https://github.com/user-attachments/assets/eb1835dc-371a-4550-bfa4-0488998d33a3)

**Comment by modos189** [comment]
How did you fix it?
