### ISSUE TITLE
debug plugin causes console statements to throw

### ISSUE THREAD

**Issue by ewoerner** [IITC-CE/ingress-intel-total-conversion#759]
In multiple circumstances, the debug plugin throws errors.

Example: `console.log(window)`
```
Uncaught RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at <anonymous>:60:16
    at Array.forEach (<anonymous>)
    at debugTab.console.renderLine (<anonymous>:57:8)
    at debugTab.console.log (<anonymous>:86:20)
    at window.console.<computed> [as log] (<anonymous>:110:31)
    at <anonymous>:1:9
```

See also bannergress/iitc-plugin#34

In general, the contract of console.something() is that it must **never** throw.

**Comment by Jormund** [comment]
This isn't specific to IITC. If you try to stringify an object with circular reference it causes recursion and fails. This error happens if you do console.log(window) in other browsers too.
