### ISSUE TITLE
ingress-intel-total-conversion/wiki/Code-Style is slightly out of date

### ISSUE THREAD

**Issue by nexushoratio** [IITC-CE/ingress-intel-total-conversion#769]
Just noticed that [Code-Style](https://github.com/IITC-CE/ingress-intel-total-conversion/wiki/Code-Style) references the recently deleted `.eslintrc.json`.

I'm not sure if there are other docs that need to be updated as well, so filing a bug rather than just updating the wiki.

@modos189

**Comment by modos189** [comment]
Thanks, updated the page
