### ISSUE TITLE
The `keypress` event is deprecated

### ISSUE THREAD

**Issue by nexushoratio** [IITC-CE/ingress-intel-total-conversion#771]
While looking into how `search.js` works, I noticed the following bit from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event):

> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

And, at least the search box uses this.

**Comment by nexushoratio** [comment]
Oh, the same is apparently true for the [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) property as well.

**Comment by nexushoratio** [comment]
And the [which](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) property.

It's a trifecta for `search.js`.

**Comment by McBen** [comment]
`Keypress` and `Keycode` are marked deprecated for more than 8years.
they are still in use by many scripts/libs (including JQuery, JQueryUI, Leaflet, Leaflet draw).
so nothing to hurry.

"which" is only used as fallback if none of the others is available.

in iiitc is appears in boot.js, idle.js, redeeming.js and search.js
It can be replaced by `keydown` and `event.key`
like:
`$("#me").on("Keydown", e=> if (e.key==="Enter") ....`
