### ISSUE TITLE
Unable to close "info screen" on Firefox on Android

### ISSUE THREAD

**Issue by nexushoratio** [IITC-CE/ingress-intel-total-conversion#781]
Maybe this isn't a supported configuration, but I thought I'd give it a try.

Rather than installing the standalone IITCm app, I would prefer to use to Firefox on Android, particularly since it is now more amenable to extensions.  This particular problem happens with both the IITC button and Violentmonkey US managers.

It starts out looking good:
![Screenshot_20241110-122625](https://github.com/user-attachments/assets/62842fa9-de52-4150-9bb8-488522e55dfe)

When I select a portal it looks good, and I can dismiss the view using the `[X]` button:
![Screenshot_20241110-122717](https://github.com/user-attachments/assets/e93180c7-60e0-4a68-ad58-0c7c019a1e3c)

But, if I just use the `tap here for info screen` button, well, I have not yet figured out how to dismiss the dialog:
![Screenshot_20241110-122205](https://github.com/user-attachments/assets/7a691bad-8875-4c26-ba49-fdbcaed9f495)

Is this simple user error, a bug, or simply an unsupported configuration?  If the last, would you be willing to accept patches to support it better?

**Comment by xscreach** [comment]
I'd say it's exactly that - unsupported configuration. 
For mobile, you should use iitc mobile where you'll see an additional top bar with a back button/arrow.

But this should be worked on as until now-ish it wasn't possible to run iitc on mobile any other way except using the mobile app.

Or you can check out this plugin that claims to solve exactly that - https://iitc.app/community_plugins#mobileimprovements-by-DanielOnDiordna

**Comment by DanielOndiordna** [comment]
I also encountered this problem (back in 2021) and I have created this plugin for that specific reason:
[https://softspot.nl/ingress/plugindetails/iitc-plugin-mobileimprovements](https://softspot.nl/ingress/plugindetails/iitc-plugin-mobileimprovements)

**Comment by nexushoratio** [comment]
That plugin works perfectly.  Thanks!

I thought I had seen this referenced somewhere but I didn't think to check the community plugins.

So, while my immediate problem is resolved, I'll leave this open for eventual native resolution.

**Comment by xscreach** [comment]
@nexushoratio I'm testing these things out now too...

Did you find a way to select active highlighter with this setup?

I couldn't with or without the mobile improvements...

Can you confirm this please 🙏

**Comment by nexushoratio** [comment]
Silly question but... what is an active highlighter?

If it includes the stuff with the checkbox like Level N portals then... with the ones I've tried so far, it works.

I haven't installed any other scripts yet.

**Comment by nexushoratio** [comment]
I should say "works".  They are very sensitive to me accidentally dragging my finger along the side, toggling things as I went along.

**Comment by xscreach** [comment]
Umh... yeah, those are very sensitive... swipe changes lot of the boxes at once...

But that's not what is a highlighter. There's whole section of those... like highlight portals based on history, portal level, recharge needed, missing resonators and such.

There's a select box in top left corner on desktop or, for mobile, there's also select box but on top of the right side panel...

![Screenshot_20241110_224312_IITC Mobile Beta.png](https://github.com/user-attachments/assets/c2201b9a-456d-4ad4-8ba6-d8cb1acb3d6b)

But i don't see anything like that with this setup (FF + tampermonkey on mobile)

**Comment by nexushoratio** [comment]
I forgot all about those.  I almost never use them because there are so many colors on the screen already!  :->

But, I see the normal highlighter drop down on the top left, and the farm level drop down on the right.  But, until I added some plugins, the highlighter drop down was not present.

![Screenshot_20241110-140010](https://github.com/user-attachments/assets/d6a6c380-956d-4807-bc2d-b4f2684f3c4f)

![Screenshot_20241110-140018](https://github.com/user-attachments/assets/6e9815fc-21b7-4f43-931e-ce1ca9b4f198)

**Comment by nexushoratio** [comment]
Also just noticed that if the layer chooser gets enough items in it, it does not get a scrollbar.

Then again, neither does the desk top if I resize it short enough.

**Comment by nexushoratio** [comment]
I can't find the bookmarks widget.  But, when I select a portal, a star shows up in the bottom left that allows me to toggle it.  But, I can't bookmark a map.

Considering that bookmarks is definitely doing something different, I suppose that different plugins are using different ways to switch into a mobile mode.  But if not everything switched (like bit of core), then there may be some things that don't work quite right.

But then, that is actually what I'm interested in finding out.  :->

**Comment by xscreach** [comment]
Lol, maybe it would be good to compile a list of things that are missing in this setup with no community plugins, but with core plugins - like those highlighters and bookmarks and such... and note community plugins that fix it... like...

* closing info panel - mobile improvements by daniel
* highlighter selection....
Etc...

Then it will be clear what needs to be incorporated into the core functionality for this kind of setup

**Comment by nexushoratio** [comment]
Agreed.  Had to start somewhere.  :-P

This bug was originally going to be only about the info panel, but sort of took on a life of its own!

Do you all have a set of github labels you want to add to such issues?  Or should there be an umbrella bug that all could block?  Or consistent naming to use?

While I may be the most annoying person (because I'll probably file lots of issues), I likely won't be the only one.

Also, what should be the end goal?

Should the aim be to make the experience between IITCm and mobile browsers be as consistent as possible?

Would an effort to provide appropriate widgets that work in all environments be worth it?

Or just wait until we get more bugs to make those decisions?

The main reason I investigated this is, for a recent plugin of my own, I created a "control panel" type widgets similar to what the Bookmarks Options and Draw Tool Options dialogs look like, only "easier" to use (well, I think so).  So I wanted to clean that up and offer it up to the community, and figured I should make sure it looks reasonable on mobile.  And well, I found a yak to shave.

**Comment by xscreach** [comment]
Well, I think the best would be to work with @DanielOndiordna on the mobile improvements plugin because it's already there... but...

@modos189 what do you think? Do we want to support firefox with "the monkeys" on mobile? 🤷‍♂️

**Comment by nexushoratio** [comment]
Is FF the only mobile browser that supports any userscript manager?   (I exclusively use Firefox on both desktop and mobile, so I have no clue what the rest of the world does.)

**Comment by nexushoratio** [comment]
That said... I think that, no matter what, it could simplify things if plugins did not have to do the work of detecting platform and UI/UX elements were provided by code/core.

**Comment by modos189** [comment]
Did you try the beta version?
https://github.com/IITC-CE/ingress-intel-total-conversion/pull/765

But the highlighters are indeed not displayed right now

**Comment by nexushoratio** [comment]
> Did you try the beta version? #765

Not yet.  Today was the first time I ever tried this on mobile.  Will try soon.

**Comment by nexushoratio** [comment]
Oh, that is nice.

It almost makes the mobile improvements plugin redundant.

The only thing that can't be done is hide the address bar.  Even with the `Scroll to hide toolbar` setting enabled.   I suppose because all events get caught to move the map around.

So, the fullscreen button on the plugin is nice for getting that small bit of real estate (and more) back.

I think you probably already noticed that the `tap here for info screen` is now redundant.  Though I'm not sure what else could go there as it is a nice indicator when a portal is selected.

I'm not keen on the use of three tabs for comms, but it is less intrusive than desktop.

In the info panel, dismissing the selected portal should probably not attempt to close the panel (going back to map).

Oh, hah!  That last highlighter I played with is now stuck in the 'on' position.


Anyway, using IITC on mobile certainly feels faster than stock intel without even using any plugins.

**Comment by modos189** [comment]
> In the info panel, dismissing the selected portal should probably not attempt to close the panel (going back to map).

It's the same behavior in IITC Mobile. And I think it's intentional: why close the portal but stay in the same panel?
Probably in the mobile version (with and without app) there is no need for such button at all, but maybe someone uses it

**Comment by nexushoratio** [comment]
> why close the portal but stay in the same panel?

I do it all the time on desktop, and immediately started doing it on mobile as well.

There are other things on the info panel besides the portal information.  That's where all of the buttons live.  I don't want it to be cluttered by a portal I've already moved on from.
